### ISSUE TITLE
API Key "unauthenticated user"

### ISSUE THREAD

**Issue by jannnfe** [Smanar/Domoticz-deCONZ#1]
Hey,
I'm new to deCONZ and RaspBee and tried to link my RaspBee with Domoticz over the weekend. However, your plugin could not connect to my RaspBee because apparently my API key is not correct. Can you tell me where to get this?
Thanks :)

**Comment by Smanar** [comment]
Have you rest application ?
I m using a firefox plugin on my side then http://dresden-elektronik.github.io/deconz-rest-doc/getting_started/

**Comment by jannnfe** [comment]
Thanks, I got it with Postman. :)

**Comment by Smanar** [comment]
NP, I have just corrected 2 big bugs (bug in color control + crash if you have too much devices)
Tell me if you still have problems.

**Comment by jannnfe** [comment]
I am just at the beginning of my deCONZ story and currently testing the system with two lamps. It seems to work very well and I am very grateful for your plugin here because it works very well so far. Thanks a lot I hope you develop the plugin even further :)
