### ISSUE TITLE
Aqara D1 double rokcer with unknown modelid

### ISSUE THREAD

**Issue by phkpr** [Smanar/Domoticz-deCONZ#100]
Hi Smanar.
Had contact with you on Discord this morning about an Aqara D1 double gang with a slightly different "modelid"
I issue an issue, since I have not enough knowledge to create a pull request.

Issue: Unknown modelid in plugin.py
Aquara D1 type#:  WXKG07LM (correctly displayed in Phoscon App)
"modelid": "lumi.remote.b286acn02", (displayed in deCONZ menu in Domoticz)

Please add 2 lines of code in plugin.py     (line# approx 600) 
          elif for lumi.remote.b286acn02
just below  
         elif for lumi.remote.b286acn01

I added some screenprints as a prove.

![Aqara-D1-backside](https://user-images.githubusercontent.com/84663565/119276088-2d96e480-bc19-11eb-91e7-0320532cb338.jpg)
![Aqara-D1-in-Domoticz-deCONZ-plugin-1](https://user-images.githubusercontent.com/84663565/119276089-2e2f7b00-bc19-11eb-9551-a877a4ced2f5.jpg)
![Aqara-D1-in-Domoticz-deCONZ-plugin-2](https://user-images.githubusercontent.com/84663565/119276090-2ec81180-bc19-11eb-913c-5289c5f4f2f1.jpg)
![Aqara-D1-in-Domoticz-deCONZ-plugin-py](https://user-images.githubusercontent.com/84663565/119276091-2ec81180-bc19-11eb-9d9e-42aa9bdb4312.jpg)
![Aqara-D1-in-Phoscon-app](https://user-images.githubusercontent.com/84663565/119276092-2f60a800-bc19-11eb-9003-03a5a3e39c63.jpg)

**Comment by Smanar** [comment]
Perfect, thx a lot ^^

Done in https://github.com/Smanar/Domoticz-deCONZ/pull/101
