### ISSUE TITLE
Dns instead ip for api

### ISSUE THREAD

**Issue by antonlamers** [Smanar/Domoticz-deCONZ#107]
Hi 
Is it possible to use a dns name instead the ip adres for making the apo key. I use domoticz in a container and somethimes after a reset the container for phoscon container has  another ip adres

**Comment by antonlamers** [comment]
The dns name is the same name as the container. I name it deconz.
The docker website says the use of the dns name from the container instead the ip adres fromt the container.

**Comment by Smanar** [comment]
Can you show the complete url you use for deconz ? with the port, and tell me is it work using a browser ?

I m not engineer so I don't know and don't use docker, but if you have a working url, I can see how to use it in domoticz.

**Comment by antonlamers** [comment]
Hi, it work in domoticz. But when I restart my iot server, the ip adres from deconz container is changing and then I must make a new API key with the new ip adres

**Comment by Smanar** [comment]
Not normal, the API key is not based on IP, I m using the same key for 3/4 hosts here.

**Comment by antonlamers** [comment]
oke, but i must make the api with python3 API_KEY.py IP PHOSCON:80 create
i thought it is based on IP

**Comment by Smanar** [comment]
>i thought it is based on IP. i did make a lot of keys, every when the ip was changed

Yep, me too, every time I use phoscon, It create a new key, after a number, you will have a message on logs to inform you

>X API keys memorised, some of them are probably useless, can use the API_KEY.py tool to clean them
