### ISSUE TITLE
Xiaomi - Aqara Temperature sensor - Temperature cannot be adjusted in Domoticz plugin 

### ISSUE THREAD

**Issue by Scoperius** [Smanar/Domoticz-deCONZ#108]
Hi, 
even I make an adjustement for Temperature in the plugin , the temperature does not change. 

![image](https://user-images.githubusercontent.com/86469550/131485723-1bdc24ee-9552-4166-92fc-f42fdaee9c63.png)
 
I made an offset  +9 °C, but no change in presented value in domoticz

The sensor is this one:
![image](https://user-images.githubusercontent.com/86469550/131485919-2c5e3839-bd2b-455c-95c7-e9ba408951bb.png)

**Comment by Smanar** [comment]
Hello, wich one deconz version have you ?

If you close the windows, and reopen it, the value is still 9 or return to 0 ?

**Comment by Scoperius** [comment]
I am using the last version you provided to me as a part of issue: https://github.com/Smanar/Domoticz-deCONZ/issues/104 

value stays after closing the window

**Comment by Smanar** [comment]
Temperatures values are * 100, so try with 900.

I m testing on my side, and have same result than you with 9

**Comment by Smanar** [comment]
Ok, so it seem working, try with * 100.
And I have updated the beta to use the "0" value with the front end.

**Comment by Scoperius** [comment]
Yes it is fine with 900, thanks Petr
