### ISSUE TITLE
Ikea TRÅDFRI smart button 403.563.81 works wierd

### ISSUE THREAD

**Issue by christoferjh** [Smanar/Domoticz-deCONZ#109]
When using the smart button (only a single button to press), it registers as selector. 
Changing to Push On makes it receive "Off" and "Sound 2".

![image](https://user-images.githubusercontent.com/18284010/132397224-3e24f222-a703-4cdb-be44-6139f25c2193.png)

**Comment by christoferjh** [comment]
Looks like using as selector with 3 levels works.
![image](https://user-images.githubusercontent.com/18284010/132398119-6dda92c5-34d2-4623-ab01-d9f929dbded4.png)

**Comment by Smanar** [comment]
And selector with all values don't work ?
Can you show the device Json ? (from logs)

I m using a generic selector by defaut for all switch but can use a specific one for this one (if it s not already done)

**Comment by christoferjh** [comment]
A selector with those 3 values works just fine, but the initial registration created a weird setup. Perhaps no action is needed and this one can be closed. But now others will know how to fix it (change to selector with the levels i posted).

**Comment by Smanar** [comment]
As you want, but if you show the complete json (to be sure for the device) I can make the code create as initial widget the one with only 3 values.

But idk what was the "weird setup" ? you can have a selector with 10 Levels but use only the 3 firsts.
