### ISSUE TITLE
Domoticz HTTPS

### ISSUE THREAD

**Issue by fernandodelucca** [Smanar/Domoticz-deCONZ#111]
Hello, my domoticz is being used through the https protocol, so when I try to access my hardware (ConBee II - Deconz) through the domoticz custom page I get the following error: 

![image](https://user-images.githubusercontent.com/5623038/135360442-1bf1d83e-94b8-467d-b2c3-a00a6c5751e1.png)

can you help me?

**Comment by gvrawake** [comment]
I have the same issue. I use domoticz with a reverse proxy over https, the deconz section is only displayed properly when I access domoticz on my internal IP

**Comment by fernandodelucca** [comment]
Correct, when I access the domoticz by the internal ip, everything works fine.
