### ISSUE TITLE
Tiny bug for windows blinds

### ISSUE THREAD

**Issue by RDols** [Smanar/Domoticz-deCONZ#112]
I think in fonctions.py line 448 the next line should be changed:

`if val == 'True':`
to
`if val == 'true':`

as for a i known, boolean string are always fully lower case, at least in my deconz. 

If you want i can change it and create an pull request, but will take a few days

Regards,
  Richard

**Comment by RDols** [comment]
Note, there are a few more 'True' with i think in wrong casing.

**Comment by Smanar** [comment]
I m not sure.
Because in python bolean are not fully lower case, It 's True and False

```
a = (5 == 5)
print(a)
```

Result
`True`

In deconz boolean are lower case, so they are lower in the json too, but when the python core use them the case is changing.

**Comment by RDols** [comment]
Yup you are absolutly right. I assumed the string was directly from json. But actually it's string representation of the a python boolean.

But the reason i looking is because my ikea blinds don't give (correct) updates, see them in the websocket events. But it updates wrong. Still debugging, but i think is because the response has multiple values.

On the websocket i find this as position update:
`{'e': 'changed', 'id': '18', 'r': 'lights', 'state': {'bri': 226, 'lift': 89, 'on': True, 'open': True, 'reachable': True}, 't': 'event', 'uniqueid': '00:0d:6f:ff:fe:aa:48:4b-01'}`

The final kwarg is:
`{'nValue': 1, 'sValue': 'Open'}`

It appears ProcessAllState will handle the next values, in the this particular order:
'on'
'bri'
'open'

Looking at [deconz api](https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/lights/#window-covering-parameters) 'bri' is deprecated and 'lift' should be used. My suggeston would be to move the if 'bri' down in the if structure and also add a if 'lift'.

I'm still debugging, so maybe i missed something and could be wrong....

**Comment by RDols** [comment]
I'm testing the above commits....

**Comment by Smanar** [comment]
@RDols Hello, somes news about your issue ?
Do you want to make a PR to change the order for "open" ? or do you want I make it ?

For the nValue, idk what is better, long time ago, somes users have asked for "stop" icon.

>Setting nValue to 2 (gswitch_sSetLevel) set the status text "Set Level: %d %%", or "Open"

there is not the slide bar to see the level status ?

**Comment by RDols** [comment]
@Smanar I finally had some time to sit down to find the problem with the blinds topping. Problem is not in the plugin, but in domoticz zwave. I have a ZRC90 switch, with a long press is open the curtains, but for some reason it sends this notification more than once, making the curtain stop.

**Comment by RDols** [comment]
For the change of order and nValue i will create a pull request. I strongly suggest for users to use the "Blinds Percentage" type for the curtains. Also tweak the settings according my comment above (https://github.com/Smanar/Domoticz-deCONZ/issues/112#issuecomment-951268071)

**Comment by Smanar** [comment]
Thx, have put a comment about the branch.
Most of covering support only on/off not the Percentage, and there is no way to detect if the device can support them using the JSON, I think it will be possible later, with the next deconz feature, the DDF file, we will have a config file by device, so will be possible to remove bri/lift if the device don't use them, and the plugin will be able to create a different widget.

**Comment by RDols** [comment]
Moved the PR to the beta branch. Will try if i can find a way to get the "stopped" back for these cases.
