### ISSUE TITLE
Wrong measurement units

### ISSUE THREAD

**Issue by fswmlu** [Smanar/Domoticz-deCONZ#13]
Hi,

my Domoticz shows wrong units for pressure and power consumption:

Aquara weather sensor: ZHAPressure / state.pressure - [Bar] instead of [hPa] (phoscon delivers the correct value)
and
 innr Smart Plug SP 120: ZHAConsumption / state.consumption - [W] instead of [Wh] and ZHAPower / state.current [W] instead of [mA].

Where can I set the rigt Unit?

Thank in advance

**Comment by Smanar** [comment]
So I have corrected the Pressure one (You will have the correction on the beta this night)
But for the seond one, you don't prefer Instant power in W instead of Power consumption W/H ? It's more "real consumption" ?

**Comment by Smanar** [comment]
Ok, I have make modification on the beta branch, if you can try it.

Just delete your bugged devices, they will be recreated when you will restart the plugin (hardware/deconz/update)

**Comment by fswmlu** [comment]
Thank you for the quick help!
Yes, pressuse value ist correct now, but the electrical values still need to be corrected... please have a look at the attachement

![Screenshot_20190404_102938_com android keyguard](https://user-images.githubusercontent.com/31476853/55542669-d4ca0200-56c7-11e9-8bc9-4b3522241bc7.jpg)

**Comment by Smanar** [comment]
Oups sorry I have seen my problem, in my head I m taking state.power in W but this values is overwrited by the state.current in mA.
it's so stupid that I do not understand why you're talking about "mA".

I will correct it immediately.

**Comment by Smanar** [comment]
So I have make a correction.
But for information in domoticz kwh device are displaying power in W in title and Consumption in kwh in description (it's for that you have "value 1 , value 2")
If I m right you will have both, but as I haven't real device so I m making simulation on my side.

**Comment by fswmlu** [comment]
Thank you! It looks much better now. Power is right now:
I see now:
![image](https://user-images.githubusercontent.com/31476853/55578647-b93a1800-5716-11e9-9d41-757236b25f0a.png)

consumption is a bit more complex:

I see 3 values: power, comsumption today and total consumption, but total consumption will be logged only at device tab:

![image](https://user-images.githubusercontent.com/31476853/55585181-5cdef480-5726-11e9-8c80-242e6fc0cf0a.png)
![image](https://user-images.githubusercontent.com/31476853/55585688-84828c80-5727-11e9-9775-0aa7b6afaaa3.png)

and the charts - power:
![image](https://user-images.githubusercontent.com/31476853/55585413-dd9df080-5726-11e9-849d-60b89d56aa66.png)

and consumption:
![image](https://user-images.githubusercontent.com/31476853/55585497-14740680-5727-11e9-9e1a-b64f5af72f44.png)

Please add the total consumtion to the "consumption" Thank you!

**Comment by Smanar** [comment]
For here you need to make a choice.
I haven't see in domoticz "total consumption" device, the only one that is close to it, is a custom counter.

So what do you prefer ?
- a "kwh" device with daily consumption and power with in log daily/weekly/30 days/years.
- a custom counter with only cumul consumption and with same log ( I think).

knowing that:
- it's possible to make a lua script to take the value in the kw device at 23h89 and add it in a counter.
- I don't know yet how will work the custom counter, need to see how domoticz manage them.

**Comment by fswmlu** [comment]
In my opinion the option 1 would be better if the value "current power [Watt]" would be reliable and I would not have the state.current. The problem is, both values are completely different:

![2019-04-06_093639](https://user-images.githubusercontent.com/31476853/55666845-8007c200-5854-11e9-8ec9-910d6bbfe79d.png)

and
![2019-04-06_093744](https://user-images.githubusercontent.com/31476853/55666850-88f89380-5854-11e9-9f3c-71a801bf0ca2.png)

 The value of power changes permanently to 0 (please watch this movie):
[Video_2019-04-06_094744.zip](https://github.com/Smanar/Domoticz-deCONZ/files/3050285/Video_2019-04-06_094744.zip)
(sorry, but I can't upload a movie file here directly)

So, in this case I think, it will be better to see the total consumtion (here 0,400 kWh)
![2019-04-06_093332](https://user-images.githubusercontent.com/31476853/55666998-bba38b80-5856-11e9-808c-252d0696d9b8.png)

on this position:
![2019-04-06_093514](https://user-images.githubusercontent.com/31476853/55667005-e68ddf80-5856-11e9-8556-d3c8c795751d.png)

What do you think? Is that possible?

The report of daily/weekly/30 days/years consumption ist perfect now:
![2019-04-06_093914](https://user-images.githubusercontent.com/31476853/55667049-9cf1c480-5857-11e9-9482-d8d8b7e6799d.png)

**Comment by Smanar** [comment]
Yep, I m thinking at this device for exemple 
![compteur](https://user-images.githubusercontent.com/20152487/55670271-b3f9dc00-5882-11e9-929e-8c8c1e4eba4d.jpg)

But I need to check how works the deCONZ comsuption on their site.
- The passage by zero is perhaps my fault, if in websocket notification you have state.consumption and not state.power.
- the notification state.power is when changing or periodically ?
- the notification for state.consumption is a total cumul or a cumul between 2 notifications (because it don't move a lot on your video) ?
- if the notification  state.consumption is periodic and state.power during chnaging ? it may explain the 0 value.

**Comment by fswmlu** [comment]
Of course I'll help you to find the best solution. Please let me know, wich logs I can send you, or wich test I can do.

> the notification state.power is when changing or periodically ?

periodically and irregulary

> Why on your video, you don't have the same value in power all the time ?

left, state.power: 183W when the TV is on, 91W - screen saver
right, state consumption: changes happened without reason

When the power value [Watt] (right on my video) will be ralistic, like value [Watt] (left), I prefer your second option. The total consumption I can find on report (/Devices/40/Report) - chart

Explanation to my video: I connected my TV, until screen saver was on, I had 183W, after that, the power consumption dropped to 91W. The changes on the right site are incomprehensible for me.

You can send me the new file, I can test it in the short term.

**Comment by Smanar** [comment]
You can try just that https://github.com/Smanar/Domoticz-deCONZ/commit/fbfd0c6875b20c8e5e0c666a2dba43a8abf37387#diff-bdcab2f88505f588ed66a949d4e6dc92
It will prevent update if deconz don't send all data eg if it miss power.

If it doesn't work, ca you send me some websocket notification about this device Somethin,g like that
```
2019-04-06 20:23:52.406 (deCONZ) ###### WebSocket Data : {'state': { ...........
2019-04-06 20:21:00.459 (deCONZ) ### Update device (Stromverbrauch Heimkino) : {......
```

**Comment by fullcavediver** [comment]
I installed the new file und started my test. First good news, both values are equal =11W und changed to 0 when I turned the switch off. I'll test it for few minutes and report to you.

Now I see a new device:
![image](https://user-images.githubusercontent.com/49302111/55674029-516b0500-58af-11e9-879c-5f9658c5c9a3.png)
Maybe the on/off switch, but I cab't use it to switch on/off the device

**Comment by Smanar** [comment]
Hu ?
There is something strange the device created for on/off the plug is a light switch.
You are sure it' s from the plug ? (with the mac adress).

This kind of device is a sensor, so it can display information , but you can't use it to send command, if you clic on it you will have this error "This device don't support action".

**Comment by fullcavediver** [comment]
I'm not developer, but I've got two accounts to :-) This is my private.

yes, you are right. the new device ist created from remote control / Ikea switch. Sorry, my problem ;-)

I've got very good news. The config ist perfect now! **Thank you! Realy, good job!**

![image](https://user-images.githubusercontent.com/49302111/55674785-854b2800-58b9-11e9-8499-c533848bfb91.png)

I compared both charts:
![image](https://user-images.githubusercontent.com/49302111/55674806-a875d780-58b9-11e9-972c-82f79e6f123d.png)

![image](https://user-images.githubusercontent.com/49302111/55674815-d0653b00-58b9-11e9-935f-e7a3df0d6e8e.png)

and the report:

![image](https://user-images.githubusercontent.com/49302111/55674830-030f3380-58ba-11e9-9f21-9de593839414.png)

Thank you, Smanar, have a nice evening.

**Comment by Smanar** [comment]
Ok, so we keep this code for the moment.
An improvement possible in future, if you have problem, is used the last power value memorised instead of ignoring missing value.

So, I m not alone with so many username and account ^^.

Thx, for bug hunting.

**Comment by fullcavediver** [comment]
Yes, maybe is it better to have more accounts 😉
The code is perfect now, you can develop it on the release page. When you need someone to check your code, lets me know. 

Thank you for the fast bug fixing and upgrade.

**Comment by Smanar** [comment]
I have just done it.
I haven't finished new device integration but I have too much bugs find, so I have just do a new release with your modifications.
