### ISSUE TITLE
kWh not measured for existing counters

### ISSUE THREAD

**Issue by jgaalen** [Smanar/Domoticz-deCONZ#131]
I have a bunch of kWh/power plugs and after the update of 8 January, the kWh counter isn't updated properly anymore (updated to 0). I've looked at the code and it has to do with the check that if also power value is received along with consumption, it tried to update sValue as POWER;COUNTER. But before my devices were already added as type 113/counter and those devices doesn't accept POWER;COUNTER. 
Perhaps make a check that if the existing domoticz device is of older device type, just set the kwh counter in the sValue instead of both values.

I have Blitzwolf plugs which adds the power (watt) value to consumption json but it always 0, so the power value is invalid anyway

**Comment by Smanar** [comment]
Ha yes, I remember this step.
If I m right the more commun widget is the same than you, the 113/counter
The other one is enabled only for the model "ZHEMI101"

And after that the code check for "power" and "consumption" presence.

So I m seing 2 way.
- Create a sensor according to presence of "power" and "consumption" in the json.
- Make a patch that correct svalue according to widget type.

I think the first method will be the better, unfortunately every time the json is corrected, the widget need to change, and you will loose all your previous values stored in database.

**Comment by jgaalen** [comment]
With 'widget' you mean 'domoticz device'?
At least for this specific case, for the Blitzwolf SHP-15, there are 2 websocket messages received after each other, 1 with power (watt) and one with consumption + power, but power is always 0 so looks like a deconz issue in this case.

I would say, once it's already created it shouldn't recreate it later, because you will loose historical data and idx will be different too. In my opinion, best way would be to match sValues with the existing domoticz device. then it's up to the user to delete the existing device to let a new one be created (it will recreate is immediately as soon as new data comes in or not?)

**Comment by Smanar** [comment]
>so looks like a deconz issue in this case

Yep, its WIP, in fact the device display the value, but this one stay  at 0, can be removed from the json.

> because you will loose historical data and idx will be different too.

Yep, bigger problem for me.

For the moment, I m using the third solution (a second whitelist), as there is only 1 device that have the both values on the same cluster.

You can try the beta branch to see if it's better for you ?
```

git pull
git checkout beta
git pull
```

**Comment by jgaalen** [comment]
Works as expected, great. With the latest beta version the sValue only contains the counter value (with my device). Thanks a lot
