### ISSUE TITLE
Current values should be in milli Ampere

### ISSUE THREAD

**Issue by jgaalen** [Smanar/Domoticz-deCONZ#132]
The new current values are shown as A, but the measurements for the Blitzwolf SHP-15 at least are in milli Amperes. Not sure if this is for every device, but perhaps the values should be divided by 1000 before passed to domoticz

**Comment by Smanar** [comment]
Hello.
Values in the API are in mA (or at least need to be) because it s generaly small value, and are send as it in domoticz.
The domoticz widget is in A and no way to use mA.

So I think this issue is for all devices.

You are using the new flag ENABLEMORESENSOR ? So it s something new as issue ?

**Comment by jgaalen** [comment]
Yes I have that flag on, and have these current/A values just recently. But currently it is showing '2380 A' for a plug which is using 555 watt, so clearly it's in mA, not A. 
As you say, the values are in mA, so if you divide the value with 1000, you will get 2.380 as a stored value, which would be right.

**Comment by Smanar** [comment]
Done, if you want to try the beta ?

```
git pull
git checkout beta
git pull
```

I hope there is not a rounding issue.

**Comment by jgaalen** [comment]
Looks good to me now, thanks again!
