### ISSUE TITLE
Ikea Blinds (Fytur) Level control

### ISSUE THREAD

**Issue by xxLeoxx93** [Smanar/Domoticz-deCONZ#134]
Hello,

I've seen in Deconz you can set a percentage of how low you want to have the blinds. For example if you set 50% it will lower it to half the way.
I've seen in Domoticz the status is reported but no way on how to set this percentage. 
Is there a hidden way on how to set the percentage from domoticz to the blinds?

Thanks as always!

**Comment by Smanar** [comment]
Hello

If I m right it's like for dimmer light. With the slider.
What is your device ? Can you show how it look in domoticz (on switch tab) and if you can the device json ?

It was a recent change on covering that remove the "stop" button and display a % instead.

**Comment by xxLeoxx93** [comment]
Hey thanks a lot! I change the type to Blinds with Dimmer and now I can use the slider. Amazing!
