### ISSUE TITLE
Support for Develco IO module - IOMZB-110

### ISSUE THREAD

**Issue by Smanar** [Smanar/Domoticz-deCONZ#135]
To test the Beta on the deconz plugin folder

```
git pull
git checkout beta
git pull
```

Then in domoticz, hardware panel / deconz / update

Delete the older widget, you will have a new one just with Unknow (invisible) "on" and "off" as possible level.
Idk if we will not have issue for the 0 value (than ca be interpreted as "off" too, else I will use B1 and B2.

**Comment by Patricen1** [comment]
Thanks!
I tried switching to beta. the behaviour is as follows:
Default status is "unknown"
Closing the switch makes the status switching briefly to "On", then back to "unknown".
Opening the switch makes the status switching briefly (but longer than when closing the switch) to "Off", then back to "unknown"

**Comment by Smanar** [comment]
Oups, my bad I forget to disable the auto "off"
You can try the new version, just with using "git pull" on the plugin folder and restart the plugin.

You will have "unknow" by defaut then "on" or "off" but stable.

**Comment by Patricen1** [comment]
It looks like that you got it!!

Wonderful! thanks

**Comment by Smanar** [comment]
Nice, I will make the change official in somes days, you have some time to test it ^^.

**Comment by Patricen1** [comment]
The application is a delay for boiler starting, the module is really convenient for this at it has both dry contacts and inputs.
Anyways, it is connected and I'll check logs to see if it works well. 
Please let me know when you make the changes, I'll then check logs.
Thanks again!
