### ISSUE TITLE
Domoticz Plugin issues

### ISSUE THREAD

**Issue by Luigi-01** [Smanar/Domoticz-deCONZ#136]
The Domoticz Beta releases are having problems with many plugins.
Somethings has changed in how Domoticz is working, many plugins are giving the wrong information or stopped working
The light (dimmer) slider for example is always 100%. 
It all started in June and I have the feeling that the Domoticz support group is not going to solve this.

I noticed on forums that many Plugins have to be re-written / updated.
The Data structure has been changed.  

Maybe you can have a look what is going on.

**Comment by Smanar** [comment]
I m using the domoticz version build 14382 ATM without issue (It's the version just after the freeze correction when reloading plugin)
But you can keep your old version, it s just the plugin code, it s work with old version without problem.

**Comment by waltervl** [comment]
For a solution perhaps check https://github.com/domoticz/domoticz/issues/5010
