### ISSUE TITLE
Error: Can't Update Unit ... BatteryLevel

### ISSUE THREAD

**Issue by arjannv** [Smanar/Domoticz-deCONZ#152]
Dear Smanar, 

I've got a very frequent error in my logs where it says it can't update a Light Level sensor. 
`2023-03-15 12:43:21.089 Error: DeConz Hub: Can't Update Unit > 159 (sensors) : {'BatteryLevel': 100}`
This happens every few minutes. 

The sensor in particular is a Aqara Motion Sensor, of which I've got a lot. 
![image](https://user-images.githubusercontent.com/43266823/225299930-9a8aa1c5-4a90-4b7c-95c7-32da6f50b6e5.png)

Is there anything I can do to solve this issue?

**Comment by Smanar** [comment]
Hello, 159 is not the unit number in domoticz but the deconz in ID in the deconz API.
You can see it directly in the API using for exemple Phoscon/ help / API Information / Sensors / ALL, and you will be able to see al id.
Else you can use direclty the URL in a browser `IP:PORT/api/APIKEY/sensors/159`

Wich one version of the plugin are you using ?

**Comment by arjannv** [comment]
Ah I see.. Running latest Beta btw. 
Unit 159 is part of the Hue Tap Dial, reporting as a `ZHARelativeRotary`. [DeConz issue](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6160)
The 4 button switch (Unit 160 in my case) is present in Domoticz, the dial is not. 

Does this device needs to be added to the plugin? Or is there a way that the plugin ignores this device? 
The most important part of the sensor (the 4 buttons) are there.

**Comment by Smanar** [comment]
>Does this device needs to be added to the plugin? Or is there a way that the plugin ignores this device?

As you want, I can add the ZHARelativeRotary, will be like the cube, you will hve a custom sensor with the expectedeventduration or exemple, IDK wich one field is the most important for you ?

**Comment by arjannv** [comment]
I won't be using it, but if it is easy it might benefit the community if we add it. 

If we would add it, we need to be able to dim lights with it. 
Don't know if this is possible, just thinking what might be convenient. But.. 
Can we have a custom sensor with the `expectedrotation` while rotating (`rotaryevent = 2`). 
And then reset the domoticz sensor to 0 when `rotaryevent = 1`. It seems that when the dial is not in use, `rotaryevent` is always 1.

This would enable the user to make an automation to dim the light relative to the start level with the `expectedrotation`.

From what is said in the DeConz disscusion, it seems that `expectedrotation` is the sum of the rotation since the start. 

> ```
> Jul 03 16:07:59 pi5 dc_eventlog[692]: /sensors/46/state: {"expectedeventduration":400,"expectedrotation":15,"lastupdated":"2022-07-03T14:07:59.382","rotaryevent":1}
> Jul 03 16:07:59 pi5 dc_eventlog[692]: /sensors/46/state: {"expectedrotation":105,"lastupdated":"2022-07-03T14:07:59.787","rotaryevent":2}
> Jul 03 16:08:00 pi5 dc_eventlog[692]: /sensors/46/state: {"expectedrotation":211,"lastupdated":"2022-07-03T14:08:00.193"}
> Jul 03 16:08:00 pi5 dc_eventlog[692]: /sensors/46/state: {"expectedrotation":256,"lastupdated":"2022-07-03T14:08:00.595"}
> Jul 03 16:08:01 pi5 dc_eventlog[692]: /sensors/46/state: {"expectedrotation":286,"lastupdated":"2022-07-03T14:08:00.996"}
> Jul 03 16:08:09 pi5 dc_eventlog[692]: /sensors/46/state: {"expectedrotation":0,"lastupdated":"2022-07-03T14:08:09.486","rotaryevent":1}
> Jul 03 16:08:09 pi5 dc_eventlog[692]: /sensors/46/state: {"expectedrotation":-30,"lastupdated":"2022-07-03T14:08:09.598"}
> Jul 03 16:08:09 pi5 dc_eventlog[692]: /sensors/46/state: {"expectedrotation":-166,"lastupdated":"2022-07-03T14:08:09.977","rotaryevent":2}
> Jul 03 16:08:10 pi5 dc_eventlog[692]: /sensors/46/state: {"expectedrotation":-226,"lastupdated":"2022-07-03T14:08:10.374"}
> Jul 03 16:08:10 pi5 dc_eventlog[692]: /sensors/46/state: {"expectedrotation":-271,"lastupdated":"2022-07-03T14:08:10.801"}
> ```

**Comment by Smanar** [comment]
> Can we have a custom sensor with the expectedrotation while rotating (rotaryevent = 2).
> And then reset the domoticz sensor to 0 when rotaryevent = 1

No problem, but its not better to keep the last value ? if you take the value in your automation, the value will be 0 at the end, no ?

**Comment by Smanar** [comment]
@arjannv have you try the beta branch ?

**Comment by arjannv** [comment]
Hi Smanar, Sorry! Should have responded earlier. 
Thanks for the change! I've updated the plugin and I can see the rotation sensor in Domoticz. 
No errors found thus far, I will check tonight if it behaves in a useful manner :)

**Comment by arjannv** [comment]
Sorry, being late again. 
Everything is working fine as expected. Thanks!
