### ISSUE TITLE
Add support for ZHAParticulateMatter

### ISSUE THREAD

**Issue by arjannv** [Smanar/Domoticz-deCONZ#158]
DeConz made some changes to the reporting of particulate sensors like the Ikea Starkvind. 
These sensors now reports the measurements as a ZHAParticulateMatter instead of ZHAAirQuality. 

Could you please add this sensor type ZHAParticulateMatter?

Thanks in advance!

Linked PR:
https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7248

**Comment by Smanar** [comment]
Hello, can you try the beta branch, on the plugin folder

```
git pull
git checkout beta
git pull
```

Then delete your device in domoticz, and reload the plugin (hardware/deconz/update)
It will be re-created, and I hope working better.

**Comment by arjannv** [comment]
Thanks for the quick update. Everything is working fine :)

**Comment by arjannv** [comment]
Hi Smanar, 
Could you also add this change to the extended branch? 
Thanks!

**Comment by Smanar** [comment]
Done, but untested, tell me if you have problem.
