### ISSUE TITLE
Xiaomi multi sensor - higrometer value without string 'Humidity'

### ISSUE THREAD

**Issue by fullcavediver** [Smanar/Domoticz-deCONZ#17]
Hi Smanar,

please make one more correction for Xiaomi multi sensor - remove the string 'Humitity' from the value, beacuse the value string is to long for some views, like floor plan.

![image](https://user-images.githubusercontent.com/49302111/56022898-f8ff9180-5d0c-11e9-9f7f-a40ae97782d5.png)

![image](https://user-images.githubusercontent.com/49302111/56023024-43810e00-5d0d-11e9-865f-9cf54ce3cd34.png)

Thank you.

**Comment by Smanar** [comment]
Not sure I can do something.
The better solution is for me a custom percent sensor, but I need to check if the humidity device have something usefull (Ithink not).

**Comment by Smanar** [comment]
On the humidity device I can add

```
Humidity_status can be one of:
    0=Normal
    1=Comfortable
    2=Dry
    3=Wet
```

**Comment by fullcavediver** [comment]
Hi Smanar,

sorry for the long dely.

I thought it was a small thing. It's just a blemish. I like your idea to add the status value. It‘s not solution for the long string, but it‘s a userful enhacement. Please lets me know, when can I test it.

THX

**Comment by Smanar** [comment]
It's a "default" from domoticz, if you take a look on all humidity device in domoticz you will have this useless word.
I can use a percent device, but it's not realy the same thing for domoticz : not the same icon, no special feature like confort status, not same tab (percent go on "mesurement", humidity go on "temperature", ect ...)

I have just add the "humidity sensation", you will have it in the device description "Dry/Comfortable/Wet"

**Comment by fullcavediver** [comment]
Do you know the limits of Comfortable, Dry and Wet? If I use the old fonctions.py, I see "normal" at the moment, if I use the new one from beta branch, the value changes to "Comfortable". What is the difference between "normal" and "comfortable"?
Unfortunately I see your update only on the temperature and dashboard/favorite tab. On the floor plan there is no difference. It's a default seting from Domoticz?

**Comment by Smanar** [comment]
Yep, it's domoticz that decide what need to be displayed. And it s something random, for exemple the leak sensor haven't the same icon on floor plan and the dashboard, the "water leak" only works on floor plan.

I have take values from a real hygrometer ^^ >> https://www.hygrometre.net/wp-content/uploads/2016/11/tfadostmannhautepr%C3%A9cision_1.jpg

For me normal mean nothing, you don't have this value anymore, you will have only "Dry/Comfortable/Wet" like the real hygrometer.

**Comment by fullcavediver** [comment]
Perfect, thank you! Well, I'll use the new file with "comfortable" instead of the "I have no idea" ;-)

![image](https://user-images.githubusercontent.com/49302111/56095417-0a979380-5edd-11e9-8de9-bbfef98c41aa.png)

Til I get the other sensors, the interface will work perfectly and I'll learn english :-D

**Comment by fullcavediver** [comment]
I am looking forward to the Ikea's smart Trådfri blinds ;-)

**Comment by Smanar** [comment]
Lol, Domoticz don't translate this status ?
Same here, I can understand why sometime the application translate some things and not other ? Like the combobox in debug configuration.

Tradfri blind have been delayed, nope ?

**Comment by fswmlu** [comment]
Yes, unfortunately, Tradfri blinds are not available yet. I see, the has been delayed again - until August :-(

**Comment by abertolin** [comment]
Hello, maybe is not the right place, but I don't know where to write :)
Is it possible to add the battery level for these sensor ? I can read it from the API, so maybe is enough to add the battery device.
Thank you !

**Comment by Smanar** [comment]
Hi, normally, it have.
There is a bug on deconz version < 65, but if you can read it from the api it's strange, in the bugged version you have "null" as battery value on API.
If you have just added the device, you need some hours to have battery report.

**Comment by Smanar** [comment]
You have it now ?

**Comment by abertolin** [comment]
Hi Smanar,
thank you for you help, my configuration is:
Product: RaspBee
Version: 2.05.64 / 22/4/2019
Firmware: 26330500

From the API, for each sensor, i have the filed "battery: 91" 

At the moment I have 4 Xiaomi multisensor and I can see (via API) the level mattery of all of them

I don't think it's a problem "of time" because I've installed the plugin 5 days ago and i still can't see the battery level:

![immagine](https://user-images.githubusercontent.com/38106893/59177655-02ff0e80-8b5d-11e9-9fff-19334f57165a.png)

**Comment by abertolin** [comment]
I updated deCONZ to the deconz-2.05.65-qt5.deb ... I'll check if something will change

**Comment by abertolin** [comment]
Ok, it work, i can read the battery level if i pass over the battery icon !

**Comment by Smanar** [comment]
Ha yep, I had same reaction 1 month ago with the last domoticz version, it's realy discrete now.

**Comment by abertolin** [comment]
Hello,
sorry, I'm here again :(
can you eplain me why, after a couple of hours that the plugin is working properly, it suddenly start to prduce errror like: 

2019-06-14 11:57:36.038 Error: (Zigbee Sensors) More than 5s timeout, Your system seem frezzed, Forcing disconnect for : GET /api/9461CE426E/config/ HTTP/1.1
2019-06-14 11:57:36.038 Host: 127.0.0.1:80
2019-06-14 11:57:36.038 User-Agent: Domoticz/1.0
2019-06-14 11:57:36.038 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
2019-06-14 11:57:36.038 Connection: keep-alive 

the only way to make it work again is to go in the hardware panel, select the plugin, change something (for example the debug level) and press "Update" ...

At this point everything work again for a caouple of hours ... and then start again with the errors ...

Thank you for your help.

**Comment by Smanar** [comment]
You have this error when the conbee take more than 5s to answer to a request.

In normal way, it will print this error message and retry, if you have this message again, and again, it mean the conbee webserver don't answer at all.
You can try to connect yourself in an internet explorer > http://127.0.0.1/api/9461CE426E/config/ for exemple, use your conbee IP, and port if you doesn't use 80, and the not working url, to check if the webserver is still working.

if you have this message only 1 time but randomly can you give me the domoticz logs before this message error pls ? You will have in log lines starting with "Send Command XXX (Y)".

You have deconz and domoticz on same machine ? if yes, wich one IP have you used ?

**Comment by Mats80L** [comment]
Mine also does that time out thing

I think it might have started after updating to deconz 2.05.65
After that I dont get updates on the devices

Just before the timeout i see this strange error
2019-06-14 20:36:50.363 (DeConZ) Pushing 'onMessageCallback' on to queue
2019-06-14 20:36:50.363 (DeConZ) Processing 'onMessageCallback' message
2019-06-14 20:36:50.363 (DeConZ) Calling message handler 'onMessage'.
2019-06-14 20:36:50.363 (DeConZ) onMessage called
2019-06-14 20:36:50.363 (DeConZ) Incomplete trame, miss 193 bytes

Pulled plugin 1.0.9 from beta branch and have the same issue

**Comment by Smanar** [comment]
"After that I dont get updates on the devices" so the websocket have stoped working too ?

This error message is normal, it's just to inform you the trame is not complete and need another "onMessage call".

Can you send me (on pastebin if you prefer) all the first lines you have in log when you restart the plugin ? To restart the plugin just clic on "update" after selecting "deconz" in hardware. You can set debug on "debug info only", it will be enought.

Have you tried, to connect on deconz whith your internet brower ? http://deconzIP/api/9461CE426E/config/

**Comment by abertolin** [comment]
Hello Smanar,
I have no problem to query the web services from a browser, I can see the settings and the sensors pages without problem.
I also have the feeling that everything started from the moment I updated the deconz version to the 2.05.65 as Mats80L said.
Today I also tried to downgrade to the version 2.05.60 that I had before, but I still have the error and the value of the sensors in Domoticz is not updated anymore.

**Comment by Smanar** [comment]
Oups, sorry guys, lol, as you are all in same issue, I have mixed you.

One of you can send me the firsts debug lines ? to see if the connection are correctly etablished ?

So, when you restart the plugin, all works fine, during some hours then you have the tiemout error. And no return from websocket, even at start ?

Wich one procedure have you used to make update ?

**Comment by abertolin** [comment]
I remove the old package with apt and I installed the new one.
The version of Domoticz is v4.10902
I'm sorry, I can't give you the log now: I'll be away for the next week.
I'll be able to send it after the 24th.
Thank you

**Comment by Smanar** [comment]
NP, I will try the same domoticz version, to try to  reproduce bug.
Sometime this some change when updating deconz, but I haven't it on my side so I can't find what could be changed.
If using browser you can connect to deconz webserver, there is no reason you can't with domoticz, so it's perhaps a "new feature" in domoticz connection framework.

On my side for installation I just downloading the archive and install it, I have do that before the 65 was official, but I don't think they have changed something in files.

**Comment by Smanar** [comment]
Ok so the bug is from domoticz, same bug after update, I m searching a solution.

**Comment by abertolin** [comment]
Thank you!!

**Comment by Smanar** [comment]
Ok so, I m rewritting the code.
Not finished yet, but working https://github.com/Smanar/Domoticz-deCONZ/issues/20

**Comment by abertolin** [comment]
Hi,
Thank you very much !!
Now it work smoothly !!
Bye
Andrea
