### ISSUE TITLE
Xiaomi Cube clock wise

### ISSUE THREAD

**Issue by czasas** [Smanar/Domoticz-deCONZ#30]
Hello is there any option to add clock wise rotate to domoticz (Magic Cube), I have only those options:
Level | Level name | Order |  
-- | -- | -- | --
0 | Off |   |  
10 | Shak |   |  
20 | Wake |   |  
30 | Drop |   |  
40 | 90° |   |  
50 | 180° |   |  
60 | Push |   |  
70 | Tap

In logs theres no info about rotating clock wise like potentiometr. I saw that options is in Xiaomi gateway  plugin.

**Comment by Smanar** [comment]
Hello (again, I m thorgal on domoticz forum).

Have you tried, the tip for better inclusion ? If the device is correcly on deconz you will have 4 device on domoticz logs on startup or 5 if you take a look in the API.
On domoticz you will have 1 device for state (it's the one you describe) and a second device for the cube with analogic value, this device will be in the Tab "Utility" juste between "Weather" and "setup"

**Comment by czasas** [comment]
Problem solved, thanks a lot :)
