### ISSUE TITLE
[support request] Hue Motion Outdoor Sensitivity

### ISSUE THREAD

**Issue by salopette** [Smanar/Domoticz-deCONZ#32]
Hi, the Hue outdoor motion detector has multiple sensitivity values, battery level.

Can you do something synonymous to adjust in Domoticz? Like you did with my thermostat ?!

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1815

**Comment by Smanar** [comment]
Something synonymous ?
For thermostat I can understand, it's something you can move every 5/10 days, but for a motion detector, you set it one time, and it never change, no ?

BTW you set it with a curl command 
`curl -H 'Content-Type: application/json' -X PUT -d '{"sensitivity": 1}' http://192.168.1.1:80/api/36E138295E/sensors/15/config`

Or here, a LUA sample https://github.com/Smanar/Domoticz-deCONZ/wiki/Examples-to-use-LUA-to-change-setting-on-the-fly.

**Comment by salopette** [comment]
Yes you are right, you do not have to change it all the time.
It was just a thought of me!

I use Gui version

**Comment by Smanar** [comment]
Nice, realy good ^^.
So if you use the GUI version, you can use deconz to set the sensitivity.
>k in the deCONZ GUI that the Sensitivity attribute is shown in the Cluster Info panel for the Occpancy Sensing cluster? If you double-click the attribute, can you read its value?

You can edit it too, then press write.

**Comment by salopette** [comment]
Yes, I found that, so I came to the idea with the selection switch. :-)

**Comment by Smanar** [comment]
It's possible too, just using domoticz
1 - Make a selector switch
2 - put all curl command in action

But I don't thnik this switch will be usefull.
