### ISSUE TITLE
Xiaomi Vibration Sensor - missing Temperature in DZ

### ISSUE THREAD

**Issue by flopp999** [Smanar/Domoticz-deCONZ#38]
I am running Domoticz 4.10730, Domoticz-deCONZ 1.0.11, Dresden ConBee 2 firmware 26490700, Phoscon 2.05.69.

I have 2 Xiaomi Temp/Hum, 1 Xiaomi Vibration, 1 Xiaomi Motion, 2 IKEA Bulbs and 1 IKEA motion.

My problem is Xiaomi Vibration. I get motion detection to Domoticz but not the temperature. I see a temperature value in Phoscon. Is it possible to get Temperature to Domoticz?

**Comment by Smanar** [comment]
Hello,
And no, temperature on other sensor than temperature sensor aren't reliable, and are not used.
