### ISSUE TITLE
Problem after Domoticz Update 

### ISSUE THREAD

**Issue by salopette** [Smanar/Domoticz-deCONZ#44]
Hi.  I just did an update in domoticz, now there is always an error message.

startup, retrying !!
2020-02-02 13:20:12.044 Error: (deconz) Wrong startup, retrying !!
2020-02-02 13:20:22.025 Error: (deconz) Wrong startup, retrying !!
2020-02-02 13:20:32.048 Error: (deconz) Wrong startup, retrying !!
2020-02-02 13:20:42.037 Error: (deconz) Wrong startup, retrying !!

**Comment by Smanar** [comment]
It mean deconz is not ready.
Go in phoscon / Gateway, I think you haven't firmware version displayed ?

**Comment by salopette** [comment]
yes you are right, deconz got stuck again and didn't start up.
I couldn't check it on the go!

**Comment by Smanar** [comment]
You have updated all the OS (for buster) or only the domoticz application ?
You have both deconz and domoticz an same machine ?

**Comment by salopette** [comment]
I have a Pi3 with Deconz and a Pi3 with domoticz.

**Comment by Smanar** [comment]
Ha ok, so you have too problem with the raspberry that have deconz ?
You are using desktop or headless version ?
How are you making the autostart ? Service/script/other ?

**Comment by salopette** [comment]
I made no changes, just downloaded and installed SD Image.

**Comment by salopette** [comment]
pi@phoscon:~ $ sudo dpkg -i deconz-latest-beta.deb
(Reading database ... 96970 files and directories currently installed.)
Preparing to unpack deconz-latest-beta.deb ...
Unpacking deconz (2.05.71-raspbian-stretch-beta) over (2.05.71-raspbian-stretch-beta) ...
Setting up deconz (2.05.71-raspbian-stretch-beta) ...
Processing triggers for gnome-menus (3.31.4-3) ...
Processing triggers for desktop-file-utils (0.23-4) ...
Processing triggers for mime-support (3.62) ...
pi@phoscon:~ $

**Comment by Smanar** [comment]
Ok, so you have standard installation without custom part.
And deconz doesn't start ATM ?

**Comment by salopette** [comment]
actually it starts automatically, but sometimes not, you have to restart the Pi dan. I don't know why either.

**Comment by Smanar** [comment]
You can try with the headless version even you have the desktop version.
And you can switch from one to other when you want.

```

Headless Mode :

    $ sudo systemctl disable deconz-gui
    $ sudo systemctl stop deconz-gui
    $ sudo systemctl enable deconz

Gui mode:

    $ sudo systemctl disable deconz
    $ sudo systemctl stop deconz
    $ sudo systemctl enable deconz-gui
```

You will loose lot of feature with headless mode, but I have see from deconz github, some user have less starting problem with it.

**Comment by salopette** [comment]
thank you, i will try and watch!
