### ISSUE TITLE
Readd removed device?

### ISSUE THREAD

**Issue by xxLeoxx93** [Smanar/Domoticz-deCONZ#48]
Hi there,
I added a switch that wasn't working probably, so I deleted the device in Domoticz & deCONZ and readded it in deCONZ. Now it's working in deCONZ but missing in Domoticz. Is there any way to get it back in the device tab?
I thought readding it in deCONZ will aadd it also again in Domooticz.

**Comment by Smanar** [comment]
Yep, you are right.
If you use it, the plugin will detect it and re-add it.
You have perhaps a problem, because it's an uniqueid already memorised by the plugin.
So just restart the plugin, it will resynchronise domoticz and deconz fron zero.

Hardware panel / deconz / "update" button.

**Comment by xxLeoxx93** [comment]
Hey,
thanks for the very quick response! Worked like a charm, I can see it now again.
Thanks a lot!
