### ISSUE TITLE
Domoticz Crashing when deCONZ is enabled

### ISSUE THREAD

**Issue by xxLeoxx93** [Smanar/Domoticz-deCONZ#49]
Hi there,

today I added a new Xiaomi Plug in Phoscon and wanted to add it in Domoticuz afterwards.
However domoticz crashed, so I restarted it with the result that 30 later it crashed again.
So I checked the log and it seems like once the Plugin gets loaded, Domoticz simply reashes:
Last lines of my log:
```
2020-03-01 13:07:47.504 (ConBee2) ### Update device (Ersatz - Office Sofa Lampe Power) : {'nValue': 0, 'sValue': '6', 'TimedOut': 1}
2020-03-01 13:07:47.504 (Ersatz - Office Sofa Lampe Power) Updating device from 0:'6' to have values 0:'6'.
2020-03-01 13:07:47.508 (ConBee2) ### Device > 41 Name:Consumption 41 Type:ZHAConsumption Details:{'consumption': None, 'lastupdated': 'none'} and {'on': True, 'reachable': False, 'temperature': 2800}
2020-03-01 13:07:47.508 (ConBee2) ### Update device (Ersatz - Office Sofa Lampe Consumption) : {'nValue': 0, 'sValue': '0', 'TimedOut': 1}
2020-03-01 13:07:47.508 (Ersatz - Office Sofa Lampe Consumption) Updating device from 0:'0' to have values 0:'0'.
2020-03-01 13:07:47.363 Status: (ConBee2) Firmware version : 0x264a0700
2020-03-01 13:07:47.363 Status: (ConBee2) Websocketnotifyall : True
2020-03-01 13:07:47.508 Error: Domoticz(pid:6156, tid:6159('PluginMgr')) received fatal signal 11 (Segmentation fault)
2020-03-01 13:07:47.508 Error: siginfo address=0x180c, address=(nil)
2020-03-01 13:07:49.895 Error: Domoticz(pid:6156, tid:6173('XiaomiGatewayIO')) received fatal signal 11 (Segmentation fault) while backtracing
2020-03-01 13:07:49.895 Error: siginfo address=0x44, address=0x3dfe90
```

When I dissable the addin, domoticz runs fine.
I've verified that I'm on the latest version of the plugin and also reinstalled it (1.0.12).
Domoticz Version: Domoticz V4.11740

**Comment by Smanar** [comment]
OK, so bad news for you.
Last beta domoticz are now incompatible with lot of machine, for exemple you need inevitably buster to don't have problem.

Lot of users had this problem and only 2 solutions have worked
- Complete re-installation from scratch
- Code recompilation

For code recompliation https://www.domoticz.com/wiki/Build_Domoticz_from_source
It will make a domoticz version according to your libs and versions.

**Comment by xxLeoxx93** [comment]
Hey, thanks for the quick reply.
What do you mean with "Complete re-installation from scratch"? Do I only need to setup Domoticz again or also Phoscon (repairing of each device)?

I tried to remove the switch from Phoscon web but I can't. I can click remove but it's still there... Then I realized that my deConz isn't correctly and I can't contol some of the switches.
So I guess the last smart plug messed something up and hence causeing issues in domoticz.
Do you have any idea what I can do to remove the device? Thnaks!

**Comment by Smanar** [comment]
Forget the complete re-installation, if it s broken suddenly (without updating the system) it can't be the problem.

Do you have the deconz version with GUI ?

We can try directly using the API
- Go to the url htt p://IPDECONZ:PORTDECONZ/api/APIKEY/sensors
You will see a JSON with all your sensors
- locate the broken device, to have the device ID
- Use Curl to remove it using something like

`curl -X DELETE http://IP:PORT/api/KEY/sensors/ID`

**Comment by xxLeoxx93** [comment]
Hey,

I managed to delete the device, unfortunalty domoticz still crashes when I enable the addin.
I restored also a backup from last night to make sure - no luck. Once the ConBee plugin starts domoticz gets unreachable.

I've access to the gui via VNC if that helps.

**Comment by Smanar** [comment]
So deconz is working now ? You have solved your problem on it ? So We don't need to use the GUI.


If domoticz don't crash immediatly, for exemple if you have this lines
>2020-03-01 13:07:47.363 Status: (ConBee2) Firmware version : 0x264a0700
2020-03-01 13:07:47.363 Status: (ConBee2) Websocketnotifyall : True

Enable log in plugin " debug info only"
If I m right, you will see before the crash
>2020-03-01 18:17:56.236 (deCONZ) Making Request  XXXXXXXXXXXXXXXXXXXXXXX

Else Enable full log

I think there is a answer from one request that are not "digest" for domoticz. At the startup domoticz ask for group/light/sensor/config, it seem it rash at one of them.

**Comment by xxLeoxx93** [comment]
Hello,

with log "Debug info only" I see this in domoticz log:
```
2020-03-01 18:24:53.324 Status: (ConBee2) Firmware version : 0x264a0700
2020-03-01 18:24:53.324 Status: (ConBee2) Websocketnotifyall : True
2020-03-01 18:24:53.507 Error: Domoticz(pid:8618, tid:8621('PluginMgr')) received fatal signal 11 (Segmentationw
```
if I set it to Full I see this as latest:

```
2020-03-01 18:26:22.400 (ConBee2) Domoticz and deCONZ are on same machine
2020-03-01 18:26:22.400 (ConBee2) Debug logging mask set to: PYTHON PLUGIN QUEUE IMAGE DEVICE CONNECTION MESSAGE
```
or do I have to access the log outside the webinterface from domoticz?

I had the latest device named with an "ü", but I've used that in an group name and it worked fine. Could it be that a "ü" is working in a group name but not in a device name?

**Comment by Smanar** [comment]
You don't have line starting with
>deCONZ) Making Request ?

Lines doesn't appear in chronological time for status or error.

**Comment by xxLeoxx93** [comment]
Hey, 
I started domoticz again and waited for 10min until I started deConz, again the last lines look like this:
```
2020-03-01 19:20:40.535 Status: (ConBee2) Started.
2020-03-01 19:20:41.203 (ConBee2) Domoticz and deCONZ are on same machine
2020-03-01 19:20:41.203 (ConBee2) Debug logging mask set to: PYTHON
2020-03-01 19:20:41.188 Status: (ConBee2) Entering work loop.
2020-03-01 19:20:41.189 Status: (ConBee2) Initialized version 1.0.12, author 'Smanar'
```
When I remove 'sensors" and 'groups' it works fine.

**Comment by Smanar** [comment]
But it crash too, even with groups disabled. Perhaps a websocket notification for a group ?

And if you remove "sensors" and not groups ? The plugin can list your group or crash directly ?

Can you show the groups json contain ? Using htt p://IP:PORT/api/API_KEY/groups/ (here or if the file is too big on pastebin) pls.

**Comment by xxLeoxx93** [comment]
`{"0":{"action":{"bri":128,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":128,"scene":null,"xy":[0,0]},"devicemembership":[],"etag":"3de5d1471446f9be75182e6892ebc3ba","id":"0","lights":["2","3","6","7","8","9","5","19","20"],"name":"Group 0","scenes":[],"state":{"all_on":false,"any_on":false},"type":"LightGroup"},"1":{"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"etag":"b413d3ddd31dfe691fb6876f5e146831","id":"1","lights":["1"],"name":"Eingang","scenes":[],"state":{"all_on":true,"any_on":true},"type":"LightGroup"},"11":{"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"etag":"5aac21e7b0a668a4a276e30cb0ae6257","id":"11","lights":["10"],"name":"Papa Schlafzimmer Neu","scenes":[],"state":{"all_on":false,"any_on":false},"type":"LightGroup"},"12":{"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"etag":"dba665c1c9f01561fba2a3c91bc8153d","id":"12","lights":[],"name":"Kueche Unten","scenes":[],"state":{"all_on":false,"any_on":false},"type":"LightGroup"},"13":{"action":{"bri":128,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":true,"sat":128,"scene":"1","xy":[0,0]},"devicemembership":[],"etag":"0c49ffa55a45873955f9abe9d21eb1bf","id":"13","lights":["15"],"name":"Esszimmer","scenes":[],"state":{"all_on":true,"any_on":true},"type":"LightGroup"},"2":{"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":["52"],"etag":"5aac21e7b0a668a4a276e30cb0ae6257","id":"2","lights":[],"name":"TRADFRI on/off switch ","scenes":[],"state":{"all_on":false,"any_on":false},"type":"LightGroup","uniqueid":"cc:cc:cc:ff:fe:4f:30:66"},"3":{"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":true,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"etag":"5dc40758b68ee8bd25eabdfe97266ce4","id":"3","lights":["2","8","16"],"name":"Office","scenes":[],"state":{"all_on":true,"any_on":true},"type":"LightGroup"},"4":{"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"etag":"db785de076ba4d51f49ab37ee54bc446","id":"4","lights":["3","9","19","20","4"],"name":"Rest","scenes":[],"state":{"all_on":false,"any_on":true},"type":"LightGroup"},"5":{"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"etag":"4eb6b29719fd61b94c6570a5a2a26727","id":"5","lights":["6","7","11","13"],"name":"Kueche","scenes":[],"state":{"all_on":true,"any_on":true},"type":"LightGroup"},"6":{"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":["55"],"etag":"5aac21e7b0a668a4a276e30cb0ae6257","id":"6","lights":[],"name":"TRADFRI on/off switch ","scenes":[],"state":{"all_on":false,"any_on":false},"type":"LightGroup","uniqueid":"cc:cc:cc:ff:fe:36:37:98"},"7":{"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"etag":"72bc5fb0b22fab057b01bf40fd9a75e9","id":"7","lights":["12","14","17","18","21"],"name":"Papa Wohnbereich","scenes":[],"state":{"all_on":true,"any_on":true},"type":"LightGroup"},"8":{"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":["56"],"etag":"5aac21e7b0a668a4a276e30cb0ae6257","id":"8","lights":[],"name":"TRADFRI on/off switch ","scenes":[],"state":{"all_on":false,"any_on":false},"type":"LightGroup","uniqueid":"cc:cc:cc:ff:fe:3d:a1:aa"},"9":{"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"etag":"daedde5254eff1fb16d58d3b2fef3046","id":"9","lights":["5"],"name":"Schlafzimmer","scenes":[],"state":{"all_on":true,"any_on":true},"type":"LightGroup"}}`
Thats the output. If I remove sensors and leave groups in its working, however I see this in the log:

```
2020-03-01 19:57:28.207 Error: (ConBee2) Websocket error, unknow device > 47 (sensors) Asking for information
2020-03-01 19:57:28.219 Error: (ConBee2) Websocket error, unknow device > 48 (sensors) Asking for information
2020-03-01 19:57:28.232 Error: (ConBee2) Websocket error, unknow device > 49 (sensors) Asking for information
2020-03-01 19:57:28.295 Error: (ConBee2) Websocket error, unknow device > 34 (sensors) Asking for information
2020-03-01 19:57:28.303 Error: (ConBee2) Websocket error, unknow device > 35 (sensors) Asking for information
2020-03-01 19:57:28.309 Error: (ConBee2) Websocket error, unknow device > 64 (sensors) Asking for information
2020-03-01 19:57:28.321 Error: (ConBee2) Websocket error, unknow device > 46 (sensors) Asking for information
2020-03-01 19:57:28.334 Error: (ConBee2) Websocket error, unknow device > 45 (sensors) Asking for information
```
A lot more of these appear now in the log. I guess this is because of teh removed sensors right?

**Comment by Smanar** [comment]
Yep, it's because the plugin detect device, and they are not initialised (we have removed the "sensor" part)
But if we disable sensor, you haven't crash ?

**Comment by xxLeoxx93** [comment]
With sensors dissabled I shouldn't recieve any temp/humid updates right? 
Because even with dissabled sensors I get temp/humidty updates!?
I've already deleted the device I added this morning so it shouldn't be in there I hope.

Sensors: https://pastebin.com/PkKcM493

**Comment by Smanar** [comment]
The JSON is valid ...

And yep, even with sensor disabled the plugin can work.
When device send information trought websocket, you will have this message
>2020-03-01 19:57:28.207 Error: (ConBee2) Websocket error, unknow device > 47 (sensors) XXXX

And the plugin ask for information and insert the sensor in domoticz.

Using this way you can add all your device one by one, but I think there is one that domoticz doesn't like.

I need to use your JSON in my domoticz version to test, hoping for crash too. But my production network is busy ATM, I will make test tomorrow sorry.

**Comment by xxLeoxx93** [comment]
No hurry :) which json file do you need from me?

**Comment by Smanar** [comment]
I have used the JSON you give to me previously this one wit sensors.
But It have worked without problem (on a windows machine)

I m realy sorry but I can't locate the bug precisely.

I another to try > https://github.com/Smanar/Domoticz-deCONZ/commit/eb60639787e37e142545c692745ff300acd37f58#diff-66c71ea3faaa52c277917c951aa67921

With this code the plugin will ignore all device > 40 (on your last log, the last one was 41)

It wil not break your system, you just have less sensor working, and I hop with no crash.
If it works try to increase the value by 5
>if key > 45:

I think you have understand what I m trying to do, with this method we can locate the device that cause problem.

But it's realy strange as bug, the json is correct and have worked without probleme on my machine.

**Comment by xxLeoxx93** [comment]
Hey, first of all: Thanks for your great support with this issue!

I adjusted the code on my machine and tried with > 1, > 40, >50, >500 --> It's always work in terms of Domoticz isn't crashing, but I see this message in the log:

```
2020-03-02 17:25:28.335 Error: (ConBee2) 'onHeartbeat' failed 'TypeError':''>' not supported between instances of 'str' and 'int''.
2020-03-02 17:25:28.335 Error: (ConBee2) ----> Line 891 in '/home/pi/domoticz/plugins/Domoticz-deCONZ/plugin.py', function onHeartbeat
2020-03-02 17:25:28.335 Error: (ConBee2) ----> Line 371 in '/home/pi/domoticz/plugins/Domoticz-deCONZ/plugin.py', function onHeartbeat
2020-03-02 17:25:28.335 Error: (ConBee2) ----> Line 428 in '/home/pi/domoticz/plugins/Domoticz-deCONZ/plugin.py', function ManageInit
2020-03-02 17:25:28.335 Error: (ConBee2) ----> Line 787 in '/home/pi/domoticz/plugins/Domoticz-deCONZ/plugin.py', function SendCommand
2020-03-02 17:25:28.335 Error: (ConBee2) ----> Line 828 in '/home/pi/domoticz/plugins/Domoticz-deCONZ/plugin.py', function UpdateBuffer
2020-03-02 17:25:28.336 Error: (ConBee2) ----> Line 571 in '/home/pi/domoticz/plugins/Domoticz-deCONZ/plugin.py', function NormalConnexion
2020-03-02 17:25:28.336 Error: (ConBee2) ----> Line 442 in '/home/pi/domoticz/plugins/Domoticz-deCONZ/plugin.py', function InitDomoticzDB
```
-> Is that expected? if I comment the two new lines out it chrashes again.

**Comment by xxLeoxx93** [comment]
Update: Tested now with my updated code: 40 works, 41 crashes.

**Comment by Smanar** [comment]
But it still strange for me.
I don't see something in the code that can crash domoticz, even it temperature, it's not a problem.
In worse situation you will have a python error, not a crash ....

You don't use this device on a lua script or other thing inside domoticz that use this device ?

And if you change the code in
>if key == 41:

I think it will crash too but now with device 42.

**Comment by xxLeoxx93** [comment]
`if key == 41:` --> Still works without a crash!

**Comment by Smanar** [comment]
Seriously ?
WTF ?

**Comment by xxLeoxx93** [comment]
Yep. I now checked again with the two lines commented out -> Crash. With ==41 --> No crash.

**Comment by Smanar** [comment]
A last try
https://github.com/Smanar/Domoticz-deCONZ/commit/22980ec3aee8fd0e944470fd9970069e727e9da0#diff-66c71ea3faaa52c277917c951aa67921

As I don't see anything bad in the JSON, this code will change the value, perhaps we can find the bad value using this way

You can make a try with the code like on the link, you will have an error message "Unknow type"
So you can remove the line Type = 'XXXX'
And in last try remove the # on the line 446, but this one will create a device on your setting, you will need to delete it (you will have the information every time you will launch the plugin, you can't forget it)

**Comment by xxLeoxx93** [comment]
Hey, should it be if key == 41?
When I try it with if key == 41 it crashes.
When I also uncomment the IEEE part it's showing me:
```
2020-03-02 18:51:07.385 Error: (ConBee2) Unknow device type XXXX
2020-03-02 18:51:07.385 Error: (ConBee2) Can't Update Unit > 41 (sensors)
```

**Comment by Smanar** [comment]
And without bug if you use the fake IEEE ?

**Comment by xxLeoxx93** [comment]
Yes, then it works .

**Comment by Smanar** [comment]
>"uniqueid":"00:15:8d:00:02:4a:7d:ff-03-000c"

???

Seriously, WTF bug !

And If you remove the sensor, and re-add it, I think you will the bug again, because the uniqueid will be the same.

I think you have a bad entry in your DZ database for this device, you know a little SQL ?

Or easier, the device is already created in DZ ? so try to remove it, hoping for DZ remove the bad entry too
And restart the plugin, it will re-create the entry.

Else I hope you have a small device database .....

**Comment by xxLeoxx93** [comment]
I think I've removed it already in Domoticz - can I see somehow which device it is?
Should I also remove it from Phoscon with ""curl -X DELETE http://IP:PORT/api/KEY/sensors/ID"?
I backup my whole Domoticz Folder every night so I've enough backups + I know SQL and could remove the device directly there. But the question to me still is: How can I see in Domoticz which device is the Nr 41 in Phoscon?

**Comment by Smanar** [comment]
You have removed it just now ?
Because 
>2020-03-01 19:28:04.007 (ConBee2) ### Device > 41 Name:Consumption 41 Type:ZHAConsumption Details:{'consumption': None, 'lastupdated': 'none'} and {'on': True, 'reachable': False, 'temperature': 2800}
2020-03-01 19:28:04.007 (ConBee2) ### Update device (Ersatz - Office Sofa Lampe Consumption) : {'nValue': 0, 'sValue': '0', 'TimedOut': 1}

It mean the device is already in database, else you will have "create device X" or "IGNORED , no changes"

I think it was previously reachable, and not ATM , so the plugin set the timeout to 1.

I don't think it's usefull to remove it from deconz, because you need this device, and if you remove it and re-include it, you will have exectly the same JSON with same uniqueid. But you can try, it's not a problem.

If domoticz crash just after the device memorisation, you will see the device id in device panel, to find it use the name and the uniqueid. (it's called idx on domoticz, ID is for the plugin), and you can sort the table.

Else I m looking ATM with SQLiteDatabaseBrowserPortable, and devices are in "devicestatus" table.
It s the same table than the "device" panel.

Requete SQL to test
>SELECT * FROM DeviceStatus WHERE DeviceID LIKE '00:15:8d:00:02:4a:7d:ff%';

You will find the on/off device and the comsumption device, it's the consumption the broken one.

**Comment by xxLeoxx93** [comment]
> "uniqueid":"00:15:8d:00:02:4a:7d:ff-03-000c"
> 
> ???

Why is that ID so strage to you? I deleted the device in Phoscon and Domoticz -> Now it works perfectly again.
But If I understood you right you think once I pair it again it will cause this issue again?
Thanks again!

**Comment by Smanar** [comment]
Yep, it's my worry.
This ID is not strange at all, this is no reason for a crash.
And python script rarely crash domoticz.

I realy think there is a "problem" when domoticz have created this device in the database, perhpas you have solved it with removing the device from DZ, but I m not sure.

**Comment by xxLeoxx93** [comment]
Hello @Smanar ,
The issue reappeared today and I think I found the reason.
It's again a sensor type "ZHAConsumption" that is causing the issue (without adding a new device).
The hardware is the xiaomi zigbee smart plug and I've seen that the power (watt) and consumption (kWh) is reported seperatly. However the consumption is on all my devices empty. If I remember correctly the smart plug only sents the information for every full used kWh. In the past with the xiaomi gateway the power and consumption was reported as one device and I was able to switch to a "computed" consumption as a workaround. With deCONZ i wasn't able to do that but it's not that important to me.
The thing is I think the plugin is crashing when the smart plug is reporting the first fully used kWh. That would be the only reason I can think of since it worked fine for weeks.

**Comment by Smanar** [comment]
So the problem would not coming from the sensor entry database but from the stored values for this device ?

But how is the JSON of the device ? I have make a search on deconz and this device haven't power consumption (or not working in deconz)
So there is nothing in the json, and the device is never updated.

**Comment by xxLeoxx93** [comment]
Hello,

this is what I see in the json for the device: 
`"17":{"config":{"on":true,"reachable":true,"temperature":2400},"ep":3,"etag":"3e0c2f3fd3e063c5526d41283f33ee93","lastseen":"2020-04-27T14:34:12.853","manufacturername":"LUMI","modelid":"lumi.plug","name":"Consumption 17","state":{"consumption":69711,"lastupdated":"2020-04-27T14:34:12.853"},"swversion":"09-29-2017","type":"ZHAConsumption","uniqueid":"00:15:8d:00:02:48:12:93-03-000c"}`
It's just strange that it's always the same device type that is causeing the issue.

**Comment by Smanar** [comment]
And what you have done, to repair your installation this time ? Deleting the device again ?

Ok, so you have consumption, and only consumption, so yes if you have power too, it will be another widget.
But the value is "normal". Can it be a "too big logging table" ? if the device send too much values ?

>The thing is I think the plugin is crashing when the smart plug is reporting the first fully used kWh. That would be the only reason I can think of since it worked fine for weeks.

What are you calling "first fully used kWh", your device can stay weeks without using kw/h ?

**Comment by xxLeoxx93** [comment]
> What are you calling "first fully used kWh", your device can stay weeks without using kw/h ?
yes, I think i've read this somewhere before that the plug only transmits fully used kw/hs. ALL my consumption values are 0 kw/h. That why I thought this could be the issue.

> But the value is "normal". Can it be a "too big logging table" ? if the device send too much values ?
All my Consumption devices are empty in Domoticz, so I don't think so.

> And what you have done, to repair your installation this time ? Deleting the device again ?
I blocked the ID 17 in the code like we discussed earlier. It's not yet deleted.

**Comment by Smanar** [comment]
I realy don't understand.

So you have 0 , 0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 , 69711
I don't understand why it crash domoticz ....

But if you have other plug identical, all with 0 at consumption but without crash it can be something to explore but I don't see what can be problematic.

Do you know a little python ?
If you have some time, I will be happy if you can move the "hack".
For exemple ATM you have 
```
            if key == 17:
                return
```

in the fonction InitDomoticzDB if I m right ?

Can you try to put it for exemple in def UpdateDevice(_id,_type,kwarg) (and removing the previous one)
with 
```
            if _id == 17:
                return
```
Like this, the device will be used, but never updated, so it never receive consumption information

But theses modifications can crash again your configuration.

**Comment by xxLeoxx93** [comment]
Update: like I said before all my consumption values are empty (except one now that is displaying some fake/unrealistic value):

![image](https://user-images.githubusercontent.com/61089790/80727505-1664f080-8b06-11ea-8463-08bdce6410d8.png)

However when I look into the device tab it seems that they have a value, but the value is not processed correctly (Maybe because of the space after the , ?):

![image](https://user-images.githubusercontent.com/61089790/80727271-c71ec000-8b05-11ea-9817-5012a08d9f6f.png)

**Comment by Smanar** [comment]
For the bug, you can replace
>kwh = round( int(val) * 1 ,3)

by

>kwh = round( float(val) * 1 ,3)

But you will have 1116400.0 Kw/h ^^, I think you have some consumption problem.
IDK what is this value, but I don't think it's something usable.

**Comment by xxLeoxx93** [comment]
> For the bug, you can replace
> 
> > kwh = round( int(val) * 1 ,3)
> 
> by
> 
> > kwh = round( float(val) * 1 ,3)
> 
> But you will have 1116400.0 Kw/h ^^, I think you have some consumption problem.
> IDK what is this value, but I don't think it's something usable.

Yeah, the consumption is unusable for me unfortunalty. Can I somehow remove all consumption devices so that they can't cause any more issues?

**Comment by Smanar** [comment]
Yep you can remove all consumption device without problem, just with command line.

I will give the command in some hours, for the moment I m searching why you have value on device tab but not on device widget.

**Comment by Smanar** [comment]
Ok so device with energy AND power is not possible on same widget on domoticz
Instead of using the value, domoticz make addition with the previous one, and after some time the value can be big enought to crash domoticz (logically the code have error handling to prevent that, but can be an explanation to the mystery)

So I have modified the code to create a new sensor for consumption. The new code is on the plugin beta

You can delete all your consumption devices in domoticz and restart the plugin, consumption widget will be re-created with the good one.
And if you have value on device tab, you will have value on widget.

Else you can delete device from deconz, but take care, you can delete bad one.
>DELETE http://IP:PORT/api/KEY/sensors/ID

**Comment by xxLeoxx93** [comment]
> Ok so device with energy AND power is not possible on same widget on domoticz

What do you mean by that? A combination should be possible I think. Thats also how the gatway addin was showing it. Like so:
![image](https://user-images.githubusercontent.com/61089790/80736529-9002db80-8b12-11ea-8ca9-719536472188.png)
--> Current power draw and consumption in one widget.

**Comment by xxLeoxx93** [comment]
> Can you try to put it for exemple in def UpdateDevice(_id,_type,kwarg) (and removing the previous one)

--> Tried it: It crashes domoticz.

**Comment by Smanar** [comment]
Lol nice I have posted the question in domoticz and still no answer https://www.domoticz.com/forum/viewtopic.php?f=28&t=32453

I will make a try with this widget. But ATM, it's better using the beta, deleting your widget and restart the plugin, you will loose your logs, but as values as bad, it's not a big problem.

You will have new widget, with only consumption but with correct value from the sensor. And all will work.

**Comment by xxLeoxx93** [comment]
> I will make a try with this widget. But ATM, it's better using the beta, deleting your widget (in domoticz only) and restart the plugin, you will loose your logs, but as values as bad, it's not a big problem.

Only the Consumption (kw/h) or also the power devices (watt)?

Doesn't it work if you crate the widget for kw/h and feed it with the watt values? By that you could use at least the calculated kw/h usage.

**Comment by Smanar** [comment]
It's like for temperature/humidity/pression sensor.
For this device Deconz create 1 entries for each, in your situation you have a ZHApower and a ZHAconsumption, so the code is using 2 widgets.

I can add a way for the plugin mix the value itself, but the plugin will create 1 device by entry even not used + 1 mixed one

ATM we are trying using script in domoticz, the script is here not finished https://github.com/Smanar/Domoticz-deCONZ/issues/52
Need to change the widget used, if there is one possible.

**Comment by xxLeoxx93** [comment]
Beta branch worked! Now Domoticz doens't crash anymore and the Consumption-devices show values. Do you know if the reported values are the total of what the Plug reccored over it's lifespan?

**Comment by Smanar** [comment]
It's exactly the value send by the device itself.
So it depend device, some of them reset when you unplug them (or have a power off), other need an action.

**Comment by xxLeoxx93** [comment]
Should I update the beta branch again and delete the power/consumption device?

**Comment by Smanar** [comment]
The today modification concern the Xiaomi double gang.
So I think you can use the one you have already updated in this comment https://github.com/Smanar/Domoticz-deCONZ/issues/49#issuecomment-622925394

If you are talking about the dz script, it's same you can use the version you have already updated.
And you don't need to delete devices at all, just create one with general/kwh type (electricity instant + counter) and edit the 3 first lines of the script according to your devices.
