### ISSUE TITLE
Multisensor issue

### ISSUE THREAD

**Issue by Patricen1** [Smanar/Domoticz-deCONZ#54]
Hello,
I'm using Xiaomi temp sensor that also provides humidity and atmospheric pressure.
This device is seen as a multisensor device in Phoscon app, but as 3 independent devices in Domoticz using the plugin. I would like to have them combined (at least temp and humidity) so that Domoticz can calculate the dew point as it was when I was previously using Xiaomi gateway. Is there a way to fix this issue?
Best regards
Patrice

**Comment by Smanar** [comment]
It's not an issue ^^, it's a long storie, but the plugin will create 3 devices.
But you can mix them, here you have a smal LUA script or a big one that can work for all devices https://github.com/Smanar/Domoticz-deCONZ/wiki/Example-to-make-a-LUA-script-to-mix-temperature-humidity-barometer-on-the-same-sensor

**Comment by Patricen1** [comment]
Thanks a lot!
I'll then try scripts
