### ISSUE TITLE
[Q] Resetting Phoscon - same or new device in Domoticz?

### ISSUE THREAD

**Issue by xxLeoxx93** [Smanar/Domoticz-deCONZ#62]
Hello,

I've some massive issues in deCONZ(segmentation fault, can't readd some devices, almost no switch is working anymore) so I plan to reset my gateway and see it it helps.
What impact will this have on my domoticz devices? Like the history of my sensors - will the the sensor once paired with deCONZ get the same device id in domoticz or do I've to readd all devices in domoticz again and loose the history?

Thanks!

**Comment by Smanar** [comment]
Ha yes, I have see your issue on deconz github, if you can reproduce the bug I think the core dump will be usefull, you realy don't have working backup ?

For domoticz, it s not a problem, the plugin use the Mac adress to reconize devices, and make a new databse in memory every time you launch it. So all will be invisible. History will be keeped.

And the plugin can inform you if a device is missing at startup, but never delete or rename device itself, so your scripts will not be inpacted even you remove a device in deconz (this one in domoticz stay in place).

**Comment by xxLeoxx93** [comment]
Hey, I've backups from Phoscon web - but loading them causes the segmentation fault... I tried the last 3 an none of them worked. I'll create the requested core dump this weekend :)

Nice to know that I only would need to repair everythin in phoscon without beeing worried about domoticz :) Thanks!
