### ISSUE TITLE
Migrated from zigbee2mqtt to deCONZ (X needed for network map)

### ISSUE THREAD

**Issue by josemi73** [Smanar/Domoticz-deCONZ#64]
I have just migrated from zigbee2mqtt to deCONZ. With zigbee2mqtt I was able to create a network map (svg) and it was available in domoticz (custom page in machinon theme).
I love Phoscon app, but I do not understand why I need graphical environment (currently I have raspbian lite) to get zigbee network map, it would be good to get it without graphical environment, and it could be shown as a new option in Phoscon app.
I know that this proposal is not easy to implement (or perharps yes).
Thank you

**Comment by Smanar** [comment]
I can't control that, I m just using their application, but somes users have already asked that to them, and the reponse is no. there is nothing planned for that yet.

I m agree with them, using the graphical environment we can have a realy powerfull application, and using an headless OS bring nothing today.

You can use too take a look on "X-Forwarding", it is a lighter solution for headless OS, but I haven't tried it on my side.

**Comment by josemi73** [comment]
> Hello, I can't control that, I m just using their application, but somes users have already asked that to them, and the reponse is no, there is nothing planned for that yet.
> 
> I m agree with them, using the graphical environment we can have a realy powerfull application, and using an headless OS bring nothing today.
> 
> You can too take a look on "X-Forwarding", it is a lighter solution for headless OS, but I haven't tried it on my side.

Ok, I will install the graphical environment then. It is headless, I will try to use X Forward. Thank you for the information
