### ISSUE TITLE
Phoscon daylight sensor problem

### ISSUE THREAD

**Issue by GRoefs** [Smanar/Domoticz-deCONZ#65]
Hi,

Started to test Conbee-2 on RPI4.
Installation of deconz went well.
Adding two Xiaomi devices (vibration sensor and smart switch) too.
Xiaomi devices work well, but the (built-in) Phoscon sensor is giving problems. 
In the error logfile: `2020-07-27 13:45:45.416 Error: (ConBee-2) Websocket error, unknow device > 1 (lights) Asking for information`

More information:

`2020-07-27 13:57:38.764 (ConBee-2) Banned device > 1 (lights)
2020-07-27 13:57:42.119 (ConBee-2) Received 342 bytes of data
2020-07-27 13:57:42.119 (ConBee-2) onMessage called
2020-07-27 13:57:42.119 (ConBee-2) ### WebSocket Data : {'attr': {'lastannounced': None, 'lastseen': '2020-07-27T11:57:42Z', 'manufacturername': 'dresden elektronik', 'modelid': 'ConBee II', 'name': 'Configuration tool 1', 'swversion': '0x26580700', 'type': 'Configuration tool', 'uniqueid': '00:21:2e:ff:ff:05:d7:67-01'}, 'e': 'changed', 'id': '1', 'r': 'lights', 't': 'event', 'uniqueid': '00:21:2e:ff:ff:05:d7:67-01'}`

Anyone an idea how to solve? 

Thanks

**Comment by 2bbe** [comment]
Hi
Check #59 
Current beta solves this issue for me.
and remember to accept new hardware devices in domoticz

**Comment by Smanar** [comment]
Yep, @GRoefs if you can try the last beta too pls ?
If it works for you too, I will push it in stable branch.

**Comment by GRoefs** [comment]
I’ll try tomorrow evening.

 

Van: Smanar <notifications@github.com> 
Verzonden: maandag 27 juli 2020 19:41
Aan: Smanar/Domoticz-deCONZ <Domoticz-deCONZ@noreply.github.com>
CC: GRoefs <info@oxem.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [Smanar/Domoticz-deCONZ] Phoscon daylight sensor problem (#65)

 

Yep, @GRoefs <https://github.com/GRoefs>  if you can try the last beta too pls ?
If it works for you too, I will push it in stable branch.

**Comment by GRoefs** [comment]
Since I’am a newbee in linux, can you please give me the commands to install the beta? 

I started learning linux a few weeks ago and I need some help.

 

Van: 2bbe <notifications@github.com> 
Verzonden: maandag 27 juli 2020 14:52
Aan: Smanar/Domoticz-deCONZ <Domoticz-deCONZ@noreply.github.com>
CC: GRoefs <info@oxem.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [Smanar/Domoticz-deCONZ] Phoscon daylight sensor problem (#65)

 

Hi
Check #59 <https://github.com/Smanar/Domoticz-deCONZ/issues/59> 
Current beta solves this issue for me.
and remember to accept new hardware devices in domoticz

**Comment by Smanar** [comment]
```
git pull
git checkout beta
```

**Comment by GRoefs** [comment]
Sorry, proposed commands did not work on my system. After some trials, rpi4 does not start anymore. Since it is a test system, there is no backup so I have to install again.

Will need some more time.

 

Keep  you informed. 

 

Van: Smanar <notifications@github.com> 
Verzonden: dinsdag 28 juli 2020 17:00
Aan: Smanar/Domoticz-deCONZ <Domoticz-deCONZ@noreply.github.com>
CC: GRoefs <info@oxem.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [Smanar/Domoticz-deCONZ] Phoscon daylight sensor problem (#65)

 

git pull
git checkout beta
