### ISSUE TITLE
Additional pages to remove need for Phoscon

### ISSUE THREAD

**Issue by JayPearlman** [Smanar/Domoticz-deCONZ#70]
Hello @Smanar,

 I wanted to get your thoughts and feedback on adding the below pages I've created to your plugin.

[https://github.com/JayPearlman/Domoticz-deCONZ/tree/hardware_interface/frontend](https://github.com/JayPearlman/Domoticz-deCONZ/tree/hardware_interface/frontend)

The files can be copied directly in to domoticz/www/templates and then a new page will appear under the "Custom" top navigation to test them out.

The idea is that these pages provide an interface to the API and remove the reliance on Phoscon for adding devices.
This is my first time ever working with AngularJS so I am open to all comments and concerns. I have tried to follow the existing practices of Domoticz and allow for additional functionality. Some of the built in translations will work and others will not.

Everything is tested as working correctly on my home system including joining new devices, renaming devices, and deleting devices.

**Comment by Smanar** [comment]
Ha nice, lot of work.
But do I need last domoticz version to test it ? I m still on 4.11590 and I have that

![tmp](https://user-images.githubusercontent.com/20152487/91065886-4d20c280-e631-11ea-801f-531f61cfe523.jpg)

**Comment by Smanar** [comment]
Ok so I have made some test, it s realy cause of domoticz version.
I have try to switch the www folder, not working, the api haven't changed, I don't understans why it  don't work.

But it mean user that are on old domoticz version because have OS < Buster can't use it.

**Comment by JayPearlman** [comment]
Thanks for verifying the version issue. My plan was / is to download the old version and see if I could narrow down what is breaking and potentially solve it for the old versions. I am running latest stable domoticz on latest Raspbian.

I originally wanted these pages to be accessible only from the hardware tab. As this directly interacts with the hardware api and is lower level than domoticz. However, those extra pages can not be done via plugins, only hard coded.

I understand your concern about deletion. Perhaps we can address the power of the page with some warnings and extra check boxes. Like opt-in.

I also enjoyed your reaction list progression 👍

**Comment by Smanar** [comment]
Don't worry about deletion, I want to prevent that using the hardware tab, but no problem using your page, like you said it s lower level than domoticz.

I m trying to compare the file modification beetween domoticz version, to find a workaround, because it can be hard to make a version compatible with old and new version (unfortunately)

And yeah I know, you can do nothing in hardware page, I have already try to put the deconz page, not possible.

But using your way is not a problem, only 2 files I can copy in the folder at first plugin install (need to check for right access)

**Comment by Smanar** [comment]
Ok so I give up on my side to find a way to make your code compatible on old and new version ^^.
I will make a"poll" to try to check if there is so much users on older versions, but on my side I have some holiday soon, will migrate to last domoticz version I think.

Your code can be so usefull, for special config on some device for exemple.

**Comment by Smanar** [comment]
@JayPearlman 
Hello, so I have started to add a button to edit the config part in device (beetween the "log" and "rename" button.

But it seem angularJS is realy something new for me ^^. If you have some time at least to explainn me how to start ?
IDK if it s better to open a popup or a new page, the table need to be editable .....

**Comment by JayPearlman** [comment]
I've implemented your request/idea about a configuration section. That may help to show how I'm doing work inside a popup window. I plan to upload the new code tonight.

The way I approached it is to use the popup window as the interface. It gets confusing because there are different kinds of windows and each one uses completely different code methods. The best suggestion I would have is to review the different options I've implemented and see if it fits in one of those ways.

**Comment by Smanar** [comment]
@JayPearlman I have just see your code, sorry for late.
So I have tryed to continue it, with edit a config ison only visible for sensor, it display a table with value, but I have some problem to make it editable ....

IDK if I can make a PRT on your fork ?

So for the moment I have put the files here
https://controlc.com/84af5b5f
https://controlc.com/4f68015a

**Comment by Smanar** [comment]
@JayPearlman Still alive ?

**Comment by Smanar** [comment]
For information, I have put your modifications on the beta.

**Comment by JayPearlman** [comment]
Sorry for the very very late response. That's great to be in the beta.

I have not abandoned and plan to circle back around to integrating your editing parts.

**Comment by Smanar** [comment]
The code is still in beta, was the same I have make in PR on your fork (no chnage on the front end)
I install the front end only 1 time (and check for file size to be sure of the version)
And never delete it

I thinbk it s better than wrutting and deleting the file at every plugin start.

**Comment by Smanar** [comment]
I have put your code in the official branch.
Thx again ^^
