### ISSUE TITLE
Conbee-II: Firmware not connected and sensors not refreshed

### ISSUE THREAD

**Issue by Madpingoo** [Smanar/Domoticz-deCONZ#74]
Hi all,

I have a setup with:

	1) Raspberry Pi 3 Model B Plus Rev 1.3
	2) ConBee-II USB Dongle
		Version	2.05.88 / 15/10/2020
		Firmware	26660700
	3) Aeotec Z-Stick Gen5 (ZWave USB Controller)
	4) An SSD hdisk connected by USB

Further information:

- Raspberry Pi OS installed.
- deCONZ plugin for Domoticz also installed.
- Installation of deconz went well.
- I connected ZWave Controller and ConBee-II USB dongle, each one  with an "usb extension cord" (50cm) in order to avoid electronic interferences.

I don't know if these issues are linked, but please find below a couple of error messages.

-> From Domoticz logs
	"**CConnection_disconnect, disconnection request from 'USB-ConBee-II' ignored. Transport does not exist**"
	
-> From Headless Phoscon GUI
	I got often "**firmware not connected**".
	Also, even if connected, "**sensors are most of time not refreshed**".

-> From System Logs (Raspberry Pi OS)

	root@domorasp:~# systemctl status deconz
	● deconz.service - deCONZ: ZigBee gateway -- REST API
	   Loaded: loaded (/lib/systemd/system/deconz.service; enabled; vendor preset: enabled)
	   Active: active (running) since Wed 2020-11-18 10:46:08 CET; 3 days ago
	 Main PID: 24844 (deCONZ)
		Tasks: 5 (limit: 2063)
	   CGroup: /system.slice/deconz.service
			   └─24844 /usr/bin/deCONZ -platform minimal --http-port=80

	nov 21 06:25:41 domorasp deCONZ[24844]: This plugin does not support propagateSizeHints()
	nov 21 06:26:03 domorasp deCONZ[24844]: This plugin does not support propagateSizeHints()
	nov 21 08:01:57 domorasp deCONZ[24844]: This plugin does not support propagateSizeHints()
	nov 21 08:03:03 domorasp deCONZ[24844]: This plugin does not support propagateSizeHints()
	nov 21 09:55:14 domorasp deCONZ[24844]: This plugin does not support propagateSizeHints()

As I can see, all seems ok for USB port.

	root@domorasp:~# ls -lrt /dev/ttyU*
	lrwxrwxrwx 1 root root 7 nov 13 23:32 /dev/ttyUSB-ZStick-5G -> ttyACM0
	lrwxrwxrwx 1 root root 7 nov 21 12:22 /dev/ttyUSB-ConBee-II -> ttyACM1
	root@domorasp:~#
	root@domorasp:~# GCFFlasher_internal -l
	GCFFlasher V3_16 (c) dresden elektronik ingenieurtechnik gmbh
	Path             | Vendor | Product | Serial     | Type
	-----------------+--------+---------+------------+-------
	/dev/ttyAMA0     | 0x0000 | 0x0000  |            | RaspBee
	/dev/ttyACM1     | 0x1CF1 | 0x0030  | DE2212441  | ConBee II
	root@domorasp:~#

All others config details

	root@domorasp:~# cat /boot/cmdline.txt
	console=tty1 root=PARTUUID=8d7f362d-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet splash plymouth.ignore-serial-consoles
	root@domorasp:~#

**Could you please help me to check my setup and find the root-cause?**

Thanks in advance for your support and your feedback.

Regards,

**Comment by Smanar** [comment]
Hello, there is lot of issue with SSD, but yes using an USB cordon extenstion is a realy good idea.
Not possible to make test without the SSD ?

What are you using as power supply ?

>I got often "firmware not connected".

The disconnection take at least some hours before happen ? BTW, there is log visible in phoscon now, in "help" part, easier to see disconnections.
