### ISSUE TITLE
Wrong startup, retrying

### ISSUE THREAD

**Issue by michi1g** [Smanar/Domoticz-deCONZ#77]
I changed the port of my phoscon interface today and thought I'd just have to change the port in the plugin and generate a new API Key. Unfortunately I keep getting:
Erro: Wrong startup, retrying
Any suggestions what to try next? Can't turn on my dining room lights now 👍

**Comment by Smanar** [comment]
Hello it mean, the gateway is not ready, I think if you go in phoscon you will have at firmware "not connected"
And if you take a look in log (you have it in deconz now), you will see an error about a channel change.

If you have the GUI, go to deconz config page, and change again the channel, don't forget the order


- In deCONZ GUI, click on Leave Network
- Open the Network settings
- Set the channel
- Repeatedly click Save button so the parameters get set
- Click Done
- Click Join Network

**Comment by michi1g** [comment]
I have tried your suggestions and a lot of other ones I found online. I ended up updating everything and resetting every single device :-(

**Comment by Smanar** [comment]
>updating everything

And you have loose all device too ? update don't impact on device ....

**Comment by michi1g** [comment]
I could still see all the devices mapped but couldn't connect to any of them.

**Comment by Smanar** [comment]
Ok, sorry, now it s too late, but if you haven't backup, there is a tips that can help in case of config corruption https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Network-lost-issues

But this bug don't happen suddently ...

**Comment by michi1g** [comment]
Thanks for you help. I guess something got a hiccup during my tries to get everything working again. Maybe this thread will help someone else if he/she runs into a similar problem
