### ISSUE TITLE
deCONZ custom menu stucks Loading

### ISSUE THREAD

**Issue by josemi73** [Smanar/Domoticz-deCONZ#82]
Hi
I have just uploaded to 1.0.16, and new custom deCONZ option stucks in Loading. What must I do?

![image](https://user-images.githubusercontent.com/52371223/102010482-927f1200-3d3e-11eb-8d2b-94fd77c7e7d2.png)

**Comment by Smanar** [comment]
I have never tested it on Machinon (or you just have the theme ?), wich one domoticz version you have it ?
This page use angular JS, so you need a recent domoticz version.

**Comment by josemi73** [comment]
Hi @Smanar 
I move theme to default and I have updated domoticz, and it keeps Loading.
Deconz is up and working fine 1.0.16.
What do you mean a web connection?

![image](https://user-images.githubusercontent.com/52371223/102014730-ce72a100-3d57-11eb-9270-e66019f715fa.png)

**Comment by josemi73** [comment]
It is about a CORS issue, because I am opening domoticz via https, and conbee URL is via http.
If I open domoticz via http, deCONZ page is opening fine.
I am closing the issue, I will use http as alternative when in LAN.
Regards

![image](https://user-images.githubusercontent.com/52371223/102014932-d4b54d00-3d58-11eb-97d5-174c4dfb9f6c.png)

**Comment by Smanar** [comment]
Ha yep, and I haven't found a way to use deconz API with https natively
