### ISSUE TITLE
Cant update

### ISSUE THREAD

**Issue by Havym** [Smanar/Domoticz-deCONZ#86]
Hi, i'm a beginner with domoticz and a raspberry pi but i am trying to update using your manual.

> You can later update the plugin
> 
> With command line, go to the plugin directory (domoticz/plugin/Domoticz-deCONZ).
> Run:
> git pull
> Restart Domoticz.

But after git pull the script is aborting.

```
git pull
remote: Enumerating objects: 60, done.
remote: Counting objects: 100% (60/60), done.
remote: Total 149 (delta 60), reused 60 (delta 60), pack-reused 89
Receiving objects: 100% (149/149), 56.70 KiB | 123.00 KiB/s, done.
Resolving deltas: 100% (90/90), completed with 4 local objects.
From https://github.com/Smanar/Domoticz-deCONZ
   75f6af3..bddbd77  master             -> origin/master
   b4e51e5..16b4984  beta               -> origin/beta
 * [new branch]      hardware_interface -> origin/hardware_interface
 * [new tag]         1.0.15             -> 1.0.15
 * [new tag]         1.0.16             -> 1.0.16
Updating 75f6af3..bddbd77
error: Your local changes to the following files would be overwritten by merge:
        README.md
        fonctions.py
        plugin.py
Please commit your changes or stash them before you merge.
Aborting
```
Can you help me?

**Comment by Smanar** [comment]
I think it because you have edited some files, the barbarian method is deleting the folder, and restart from begin (you will loose nothing) or try

```
git reset --hard
git pull
```

**Comment by Havym** [comment]
Yup, it worked. Thank you..

`git reset --hard
HEAD is now at d8a2dfd Update README.md
`

` git pull
Updating d8a2dfd..bddbd77
Fast-forward
 API_KEY.py           |   2 +-
 README.md            |  82 ++++---
 banned_devices.txt   |   2 -
 fonctions.py         | 333 ++++++++++++++++++++++++----
 frontend/deCONZ.html | 221 +++++++++++++++++++
 frontend/deCONZ.js   | 601 +++++++++++++++++++++++++++++++++++++++++++++++++++
 plugin.py            | 444 ++++++++++++++++++++++++++++++-------
 7 files changed, 1536 insertions(+), 149 deletions(-)
 delete mode 100644 banned_devices.txt
 create mode 100644 frontend/deCONZ.html
 create mode 100644 frontend/deCONZ.js
`
