### ISSUE TITLE
Issues enabling plugin in latest linuxserver docker image

### ISSUE THREAD

**Issue by rwijnhov** [Smanar/Domoticz-deCONZ#89]
When i try to enable the plugin in the latest linuxserver docker image i get:
2021-02-05 09:20:24.565 Error: (deCONZ) failed to load 'plugin.py', Python Path used was '/config/plugins/deconzplugin/:/usr/lib/python38.zip:/usr/lib/python3.8:/usr/lib/python3.8/lib-dynload:/usr/local/lib/python3.8/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.8/dist-packages'.

Any ideas on how to fix this? The plugin works on an old 4.17 version.

**Comment by Smanar** [comment]
Try checking the folder to see if the files are at good place
```
/config/plugins/deconzplugin/
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/usr/lib/python3.8/dist-packages
```

I think the more important is `/config/plugins/deconzplugin/`

**Comment by Smanar** [comment]
Still have problem ?

**Comment by rwijnhov** [comment]
Hi i got it working. But reverted back to domoticz and deconz on windows.
With that setup i get after a while websocket disconnected error. It works
for a couple of hours and the websocket issue. Any ideas?

Tank you,

Ruben

Op do 18 feb. 2021 om 17:18 schreef Smanar <notifications@github.com>:

**Comment by Smanar** [comment]
Websocket connection are managed by the client (so the domoticz plugin here, and I m using the domoticz connection stuff for websocket, so can be from your domoticz version too)
But the plugin don't detect the websocket disconnection ?

Something to try, there is some plugin for browser to use them as websocket client (I m using "Browser websocket client" on firefox), you can connect it in same time than domoticz, and check if both disconnect in same time.
