### ISSUE TITLE
control lights in Domoticz

### ISSUE THREAD

**Issue by LongTimeUser77** [Smanar/Domoticz-deCONZ#90]
I use Domoticz with a conbee II usb stick. 
I had a Philips bridge. when I switched my programming was not working correct anymore.
I use scenes in Domoticz to change light color and intensity. worked with the Philips hub.
now when I use scene on a light I can change the color. but I get 100% intensity.
when I try to correct the intensity it does not work. this is in the rbg mode. in between I got the white mode en latest both.
in both I can change the intensity but then the color changes to white. 
the light in Domoticz is displayed as rgbwwz dimmer.
is there a solution?

**Comment by Smanar** [comment]
Hello, 

By "scenes", you mean domoticz scenes ? not zigbee one ?
Yours bulbs support RGB and white mode ?

rgbwwz device have "3 pages".
- the first one is RGB + level
- the second one is Temperature color + level
- the third one is ... huuu.. too complicated for me.

If you are using the third one, can you explain me wich one bar is used for ?

Or it bug only on scene page ?

**Comment by LongTimeUser77** [comment]
Hello there

Dominica scène.
Controlling the lights.

[cid:8283C215-02F9-4A47-AC7E-4B7B47340CBA-L0-001][cid:2354E53E-65C0-4664-8703-5C76DB138A10-L0-001][cid:002705A9-938D-442F-8ADE-8DE1505FD78D-L0-001]

1 picture to control the light.
Only works with the colour not the intensity. Bar does nothing with the light.
2 picture everything works.
3 picture, Color selection does nothing. First bar darkers the color circle but does nothing with the light, second bar works for the white in the light. 3 bar white intensity this works. Four bar all intensity works.
But when I select and use bar 4 the light becomes white.
I cannot set a color and intensity.

Gr. Peter

Op 6 feb. 2021 om 18:12 heeft Smanar <notifications@github.com> het volgende geschreven:

﻿

Hello,

By "scenes", you mean domoticz scenes ? not zigbee one ?
Yours bulbs support RGB and white mode ?

rgbwwz device have "3 pages".

  *   the first one is RGB + level
  *   the second one is Temperature color + level
  *   the third one is ... huuu.. too complicated for me.

If you are using the third one, can you explain me wich one bar is used for ?

Or it bug only on scene page ?

**Comment by LongTimeUser77** [comment]
Sorry in picture 3
Bar 2 and 3 does nothing with the light.

Gr. Peter

Op 6 feb. 2021 om 19:30 heeft Peter B <bip757@hotmail.com> het volgende geschreven:

﻿ Hello there

Dominica scène.
Controlling the lights.

<image0.jpeg>
<image1.jpeg>
<image2.jpeg>


1 picture to control the light.
Only works with the colour not the intensity. Bar does nothing with the light.
2 picture everything works.
3 picture, Color selection does nothing. First bar darkers the color circle but does nothing with the light, second bar works for the white in the light. 3 bar white intensity this works. Four bar all intensity works.
But when I select and use bar 4 the light becomes white.
I cannot set a color and intensity.

Gr. Peter

Op 6 feb. 2021 om 18:12 heeft Smanar <notifications@github.com> het volgende geschreven:

﻿

Hello,

By "scenes", you mean domoticz scenes ? not zigbee one ?
Yours bulbs support RGB and white mode ?

rgbwwz device have "3 pages".

  *   the first one is RGB + level
  *   the second one is Temperature color + level
  *   the third one is ... huuu.. too complicated for me.

If you are using the third one, can you explain me wich one bar is used for ?

Or it bug only on scene page ?

**Comment by Smanar** [comment]
Ok, so I have find somes problem yes, I have a new code, if you can test it ?
https://github.com/Smanar/Domoticz-deCONZ/blob/beta/plugin.py

You can just replace the file (you will have github error later, but easy to solve with a command line) or install the beta.

So you have 3 mode to set a color
- mode 1 : this mode is only for pure RGB, so the level don't work for HUE, I have tried to add a fake convertion, if you can tell me if it works
- mode 2 : temperature mode, nothing special as it already work
- mode 3 only for advanced bulb, the rgb selector and the 2 firsts bar will work, but idk what I need to do with the 2 lasts ?

**Comment by LongTimeUser77** [comment]
I replaced the file but lost al my lights in deconz addon.
Try to restore know.

Gr. Peter

Op 7 feb. 2021 om 10:59 heeft Smanar <notifications@github.com> het volgende geschreven:

﻿

Ok, so I have find somes problem yes, I have a new code, if you can test it ?
https://github.com/Smanar/Domoticz-deCONZ/blob/beta/plugin.py

You can just replace the file (you will have github error later, but easy to solve with a command line) or install the beta.

So you have 3 mode to set a color

  *   mode 1 : this mode is only for pure RGB, so the level don't work for HUE, I have tried to add a fake convertion, if you can tell me if it works
  *   mode 2 : temperature mode, nothing special as it already work
  *   mode 3 only for advanced bulb, the rgb selector and the 2 firsts bar will work, but idk what I need to do with the 2 lasts ?

**Comment by LongTimeUser77** [comment]
Replaced the file but lost all my lights in domoticz deconz

Groeten Peter


Op 7 feb. 2021 om 10:59 heeft Smanar <notifications@github.com> het volgende geschreven:

﻿

Ok, so I have find somes problem yes, I have a new code, if you can test it ?
https://github.com/Smanar/Domoticz-deCONZ/blob/beta/plugin.py

You can just replace the file (you will have github error later, but easy to solve with a command line) or install the beta.

So you have 3 mode to set a color

  *   mode 1 : this mode is only for pure RGB, so the level don't work for HUE, I have tried to add a fake convertion, if you can tell me if it works
  *   mode 2 : temperature mode, nothing special as it already work
  *   mode 3 only for advanced bulb, the rgb selector and the 2 firsts bar will work, but idk what I need to do with the 2 lasts ?

**Comment by Smanar** [comment]
This code don't impact deconz, and deconz resynchronize at every new start, so don't worries, you can just rollback the file and restart the plugin (hardware/deconz/update)

But you have no errors in domoticz logs ("debug info only") ?

**Comment by LongTimeUser77** [comment]
I did restart and no custom deconz api key error.

So in my panic I restored an image.
My whole house works with domoticz.

Have to try again but a little bit .....

Peter

Op 7 feb. 2021 om 16:16 heeft Smanar <notifications@github.com> het volgende geschreven:

﻿

This code don't impact deconz, and deconz resynchronize at every new start, so don't worries, you can just rollback the file and restart the plugin (hardware/deconz/update)

But you have no errors in domoticz logs ("debug info only") ?

**Comment by Smanar** [comment]
Sure, no problem.
Else you can direclty install the beta 

```
git pull
git checkout beta
git pull
```

But seriously you don't need to restore an image, just delete the plugin folder and re install it, it take 5mn and if you use the same folder name, all is invisible on domoticz.

**Comment by LongTimeUser77** [comment]
Thx!

I will try again.
Don’t do this every day :)

Gr. Peter

Op 7 feb. 2021 om 18:39 heeft Smanar <notifications@github.com> het volgende geschreven:

﻿

Sure, no problem.
Else you can direclty install the beta

git pull
git checkout beta
git pull


But seriously you don't need to restore an image, just delete the plugin folder and re install it, it take 5mn and if you use the same folder name, all is invisible on domoticz.

**Comment by LongTimeUser77** [comment]
What  directory for pi raspberry?
Beta for deconz, domoticz or python.
I think github

Gr. Peter

Op 7 feb. 2021 om 18:39 heeft Smanar <notifications@github.com> het volgende geschreven:

﻿

Sure, no problem.
Else you can direclty install the beta

git pull
git checkout beta
git pull


But seriously you don't need to restore an image, just delete the plugin folder and re install it, it take 5mn and if you use the same folder name, all is invisible on domoticz.

**Comment by Smanar** [comment]
It s OS dependeant but for me it s 

`cd ~/domoticz/plugins/Domoticz-deCONZ`

To reach  the deconz plugin folder, then

`git pull`

To update

`git checkout beta`

To switch to beta

`git pull`

To be sure all is in dat

Then just restart the plugin (just the plugin, no need for deconz or domoticz)

**Comment by LongTimeUser77** [comment]
Thx I will try it!

Gr. Peter

Op 7 feb. 2021 om 19:16 heeft Smanar <notifications@github.com> het volgende geschreven:

﻿

It s OS dependeant but for me it s

cd ~/domoticz/plugins/Domoticz-deCONZ

To reach the deconz plugin folder, then

git pull

To update

git checkout beta

To switch to beta

git pull

To be sure all is in dat

Then just restart the plugin (just the plugin, no need for deconz or domoticz)

**Comment by LongTimeUser77** [comment]
With git pull , I got an error
File to long.
I am in domoticz-deconz directory.
Don’t no why but i keep looking.

Gr. Peter

Op 7 feb. 2021 om 19:16 heeft Smanar <notifications@github.com> het volgende geschreven:

﻿

It s OS dependeant but for me it s

cd ~/domoticz/plugins/Domoticz-deCONZ

To reach the deconz plugin folder, then

git pull

To update

git checkout beta

To switch to beta

git pull

To be sure all is in dat

Then just restart the plugin (just the plugin, no need for deconz or domoticz)

**Comment by Smanar** [comment]
You are using Vm or docker ?

Perhaps (never used, found on a forum)
`git config core.longpaths true`

**Comment by LongTimeUser77** [comment]
I am using a pi with raspbian.

When I delete you’re plug-in and try to reinstall I get a pull error.
The file is too long expected “)”

Also when I try to use the beta I get the same error.

Is the download file correct on the site?

Gr. Peter

Op 8 feb. 2021 om 16:43 heeft Smanar <notifications@github.com> het volgende geschreven:

﻿

You are using Vm or docker ?

Perhaps (never used, found on a forum)
git config core.longpaths true

**Comment by Smanar** [comment]
But you are using 
`git clone https://github.com/Smanar/Domoticz-deCONZ.git`

To install the plugin ? I have just made a test, no problem on my side. It seem this kind of error is provoked by too long path name, but on a normal Raspian I dont see how it can be possible.
You are sure your OS is updated ?

**Comment by LongTimeUser77** [comment]
I am using the link.
Updated the system. Still the Same error “file name too long”
Last week when I installed you’re program it worked.

I check further what maybe wrong.

Thx for the assist.

Gr. Peter

Op 9 feb. 2021 om 17:42 heeft Smanar <notifications@github.com> het volgende geschreven:

﻿

But you are using
git clone https://github.com/Smanar/Domoticz-deCONZ.git

To install the plugin ? I have just made a test, no problem on my side. It seem this kind of error is provoked by too long path name, but on a normal Raspian I dont see how it can be possible.
You are sure your OS is updated ?

**Comment by Smanar** [comment]
Realy strange, you have the command that provoke this error ?
To see if it s from the OS or direclty from github command ?

**Comment by LongTimeUser77** [comment]
pi@domoticzpi:~/domoticz/plugins/Domoticz-deCONZ $ git pull

/usr/lib/git-core/git-remote-https: 1: /usr/lib/git-core/git-remote-https: ????????????????????????????????????????????????????????????????????????????????: File name too long

/usr/lib/git-core/git-remote-https: 2: /usr/lib/git-core/git-remote-https: Syntax error: word unexpected (expecting ")")

pi@domoticzpi:~/domoticz/plugins/Domoticz-deCONZ $


With a lot more ????

Still looking for an answer.

Browsing the internet.

Gr. Peter

Op 9 feb. 2021 om 20:29 heeft Smanar <notifications@github.com> het volgende geschreven:

﻿

Realy strange, you have the command that provoke this error ?
To see if it s from the OS or direclty from github command ?

**Comment by Smanar** [comment]
But I don't understand ... it have already worked.
Have you tried to delete the folder and retry installing the plugin from sratch ? (Take care, you need to use exactly the same folder name, else domoticz will think it s a new plugin and disable the older one, so you will loose all your domoticz widget/automation)

Or you can try to install it at another place to test, less dangerous. If it work the problem is probably in git data for this clone.
Perhaps (to reset all the code to last master, no impact on your instalation
`git reset --hard origin/master`

The `--verbose` flag in the command give more information.

I find nothing on google on my side, rare bug.

**Comment by LongTimeUser77** [comment]
I did not delete the folder. But I did rename it.
I think I need to delete it but I have not dare to do this yet.
I will try another directory first.

Gr. Peter

Op 10 feb. 2021 om 17:56 heeft Smanar <notifications@github.com> het volgende geschreven:

﻿

But I don't understand ... it have already worked.
Have you tried to delete the folder and retry installing the plugin from sratch ? (Take care, you need to use exactly the same folder name, else domoticz will think it s a new plugin and disable the older one, so you will loose all your domoticz widget/automation)

Or you can try to install it at another place to test, less dangerous. If it work the problem is probably in git data for this clone.
Perhaps (to reset all the code to last master, no impact on your instalation
git reset --hard origin/master

The --verbose flag in the command give more information.

I find nothing on google on my side, rare bug.

**Comment by LongTimeUser77** [comment]
I tried everything what I could find on the web.
No joy.
Deleted the Domotiz-deCONZ directory.

Unable to pull the git.

I think I have to reinstall everything.

Thx for the help and thx for writing the git for domoticz.

Gr. Peter :)

Op 10 feb. 2021 om 20:53 heeft Peter B <bip757@hotmail.com> het volgende geschreven:

﻿ I did not delete the folder. But I did rename it.
I think I need to delete it but I have not dare to do this yet.
I will try another directory first.

Gr. Peter

Op 10 feb. 2021 om 17:56 heeft Smanar <notifications@github.com> het volgende geschreven:

﻿

But I don't understand ... it have already worked.
Have you tried to delete the folder and retry installing the plugin from sratch ? (Take care, you need to use exactly the same folder name, else domoticz will think it s a new plugin and disable the older one, so you will loose all your domoticz widget/automation)

Or you can try to install it at another place to test, less dangerous. If it work the problem is probably in git data for this clone.
Perhaps (to reset all the code to last master, no impact on your instalation
git reset --hard origin/master

The --verbose flag in the command give more information.

I find nothing on google on my side, rare bug.

**Comment by Smanar** [comment]
```
Deleted the Domotiz-deCONZ directory.
Unable to pull the git.

```

Still with the same error message ?

**Comment by LongTimeUser77** [comment]
Yes still with the same error.

Gr. Peter

Op 13 feb. 2021 om 14:28 heeft Smanar <notifications@github.com> het volgende geschreven:

﻿

Deleted the Domotiz-deCONZ directory.
Unable to pull the git.



Still with the same error message ?

**Comment by Smanar** [comment]
you can too download manualy the files and copy them.
But from my memory was the first thing you have tried and have broked all the plugin ?

**Comment by LongTimeUser77** [comment]
I did make a copy of the memory card before the attempt.
So it still works but unable to upgrade

Groeten Peter


Op 13 feb. 2021 om 15:36 heeft Smanar <notifications@github.com> het volgende geschreven:

﻿

you can too download manualy the files and copy them.
But from my memory was the first thing you have tried and have broked all the plugin ?

**Comment by Smanar** [comment]
But it s not possible to download this file https://github.com/Smanar/Domoticz-deCONZ/archive/beta.zip
And extract it in the folder ?

**Comment by Smanar** [comment]
I m asking for more return about your issue to make test on the domoticz topic.

**Comment by LongTimeUser77** [comment]
I just copied the files directly into the directory.

I am now able to use the light intensity in domoticz.
It seems te be working.

Still same error with git pull.

Gr. Peter

Op 18 feb. 2021 om 17:17 heeft Smanar <notifications@github.com> het volgende geschreven:

﻿

I m asking for more return about your issue to make test on the domoticz topic.

**Comment by Smanar** [comment]
So the problem is from git, not your OS ?

So all is working, even if I don't use the 2 last bars ? IDK what to do with them, never tried the HUE plugin.

**Comment by LongTimeUser77** [comment]
I will send you what it supposed to be.

Gr. Peter

Op 21 feb. 2021 om 17:07 heeft Smanar <notifications@github.com> het volgende geschreven:

﻿

So the problem is from git, not your OS ?

So all is working, even if I don't use the 2 last bars ? IDK what to do with them, never tried the HUE plugin.

**Comment by LongTimeUser77** [comment]
I had a Philips hue bridge.

Domoticz gave 2 options.

Picture one color + intensity
Picture two white + intensity

That’s it.

Maybe extras are for color and white at the same time.

But I think you don’t need picture number three.
Just remove it.

Gr. Peter

Op 21 feb. 2021 om 17:17 heeft Peter B <bip757@hotmail.com> het volgende geschreven:

﻿ I will send you what it supposed to be.

Gr. Peter

Op 21 feb. 2021 om 17:07 heeft Smanar <notifications@github.com> het volgende geschreven:

﻿

So the problem is from git, not your OS ?

So all is working, even if I don't use the 2 last bars ? IDK what to do with them, never tried the HUE plugin.

**Comment by Smanar** [comment]
Ok, so the 2 first mode are working ?
I will let the 3th, because your device need this one, if it work on mode 1, color + intensity, it s because I m making a convertion, but the official mode for this kind of devce is the 3th.

**Comment by LongTimeUser77** [comment]
The 2 first modes are working.
If it is official keep nr3.

Thx for the help!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by LongTimeUser77** [comment]
I got another question

I have a push switch from aquara.

This device is in the domoticz deconz page listed as ZHA switch from LUMI
This switch also gives temperature but is not shown in domoticz.

Is it possible for you to add this function?

Gr. Peter

Op 21 feb. 2021 om 20:10 heeft Smanar <notifications@github.com> het volgende geschreven:

﻿

Ok, so the 2 first mode are working ?
I will let the 3th, because your device need this one, if it work on mode 1, color + intensity, it s because I m making a convertion, but the official mode for this kind of devce is the 3th.

**Comment by Smanar** [comment]
>This switch also gives temperature but is not shown in domoticz.

No, temperature from other sensor than temperature sensor are never showed, not reliable, it s in the JSON because present on the hardware but not usable.

**Comment by LongTimeUser77** [comment]
I understand

I show the temperature in the hue essential app.
That’s why I was wandering if this was possible

Gr. Peter

Op 26 feb. 2021 om 09:35 heeft Smanar <notifications@github.com> het volgende geschreven:

﻿

This switch also gives temperature but is not shown in domoticz.

No, temperature from other sensor than temperature sensor are never showed, not reliable, it s in the JSON because present on the hardware but not usable.
