### ISSUE TITLE
Temperature adjustment don't work with devices created by the plugin

### ISSUE THREAD

**Issue by southmind** [Smanar/Domoticz-deCONZ#98]
I use the plugin since 2 years and it works fine with switch or XIAOMI sensor , but I am unable to set adjustment values with my temp devices...
the only way to fix that is to create a virtual temp device and to set the temp value with the one created by deConz... 
Seems to be a problem with Python plugins, the updateDevice function. 

https://github.com/domoticz/domoticz/issues/2881#issuecomment-441357383

**Comment by Smanar** [comment]
there is a setting too directly in deconz.

- Custom
- deconz
- sensor tab
- select your temperature sensor
- use the icon "edit" on the right
- the field "offset" is modifiable.

And this setting will impact all others applications that use your deconz API.

**Comment by Smanar** [comment]
So it mean it have worked ^^ ?
